<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="clGmsConfig"
    nsURI="gms.ecore" nsPrefix="gms">
  <eClassifiers xsi:type="ecore:EClass" name="GMS">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Group Membership Service"/>
      <details key="validator" value="com.clovis.cw.workspace:com.clovis.cw.workspace.validator.GMSMulticastPortValidator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="GMS_Cluster_0" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Cluster name"/>
        <details key="pattern" value="^[a-zA-Z][a-zA-Z0-9_]*$"/>
        <details key="message" value="Invalid cluster name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNoOfGroups" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Maximum number of groups"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multicastAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="224.92.92.1" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Multicast address"/>
        <details key="pattern" value="^([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])$"/>
        <details key="message" value="Invalid multicast address"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multicastPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="6051" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Multicast port"/>
        <details key="pattern" value="^(102[4-9]|10[3-9][0-9]|1[1-9][0-9]{2}|[2-9][0-9]{3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"/>
        <details key="message" value="Invalid multicast port. Value should be in the range [1024 - 65535]."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openAisLoggingOption" eType="#//OpenAisLoggingEnum"
        defaultValueLiteral="debug" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Openais logging option"/>
        <details key="UItype" value="UIOpenAisLoggingEnum"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bootElectionTimeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="5"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Boot election timeout(seconds)"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredActiveSCNodeName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="none"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Preferred active node"/>
        <details key="editor" value="com.clovis.cw.workspace:com.clovis.cw.workspace.editor.ActiveSCNodeComboBoxCellEditor"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BootConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gms" lowerBound="1" eType="#//GMS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpenAisLoggingEnum">
    <eLiterals name="none"/>
    <eLiterals name="stderr" value="1"/>
    <eLiterals name="file" value="2"/>
    <eLiterals name="syslog" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UIOpenAisLoggingEnum">
    <eLiterals name="NONE"/>
    <eLiterals name="STDERR" value="1"/>
    <eLiterals name="FILE" value="2"/>
    <eLiterals name="SYSLOG" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SCNodeNameEnum">
    <eLiterals name="none" literal="none"/>
  </eClassifiers>
</ecore:EPackage>
