<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="clIocConfig"
    nsURI="ioc.ecore" nsPrefix="ioc">
  <eClassifiers xsi:type="ecore:EClass" name="IOC">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Intelligent Object Communication"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heartBeatInterval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Heart Beat Interval"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reassemblyTimeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Reassembly Timeout"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendQueue" lowerBound="1"
        eType="#//Queue" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Send Queue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveQueue" lowerBound="1"
        eType="#//Queue" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Receive Queue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" lowerBound="1"
        eType="#//TransportType" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Transports"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstances" lowerBound="1"
        eType="#//NodeInstances" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="isHidden" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue">
    <eAnnotations source="CWAnnotation">
      <details key="Help" value="com.clovis.cw.help.boot_ioc_queue"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="0" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Size"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waterMark" lowerBound="1"
        eType="#//WaterMark" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Water Mark"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaterMark">
    <eAnnotations source="CWAnnotation">
      <details key="validator" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.validator.MemoryWaterMarkValidator"/>
      <details key="Help" value="com.clovis.cw.help.boot_ioc_watermark"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="35"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Low Limit"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="90"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="High Limit"/>
        <details key="isBlankAllowed" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//WaterMarkAction" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Action"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaterMarkAction">
    <eAnnotations source="CWAnnotation">
      <details key="Help" value="com.clovis.cw.help.boot_ioc_watermark_action"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//EventAction"
        containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Event"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notification" lowerBound="1"
        eType="#//NotificationAction" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Notification"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="log" lowerBound="1" eType="#//LogAction"
        containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Log"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="custom" lowerBound="1"
        eType="#//CustomAction" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Custom"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Enable"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotificationAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransportType">
    <eAnnotations source="CWAnnotation">
      <details key="validationfeatures" value="transportName"/>
      <details key="label" value="Transport"/>
      <details key="Help" value="com.clovis.cw.help.boot_ioc_node_transport"/>
      <details key="validator" value="com.clovis.cw.workspace:com.clovis.cw.workspace.validator.TransportIDValidator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportName" eType="#//Transport"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Transport Name"/>
        <details key="pattern" value="^[a-zA-Z][a-zA-Z0-9_]*$"/>
        <details key="message" value="Invalid Transport Name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="6736" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Transport ID"/>
        <details key="isBlankAllowed" value="false"/>
        <details key="pattern" value="[0-9][0-9]*"/>
        <details key="message" value="Transport ID cannot be blank"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Transport Priority"/>
        <details key="pattern" value="^[0]*[1-9][0-9]*$"/>
        <details key="message" value="Priority is a number and should be greater than zero"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//LinkType"
        unsettable="true" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Links"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkType">
    <eAnnotations source="CWAnnotation">
      <details key="NameField" value="linkName"/>
      <details key="validationfeatures" value="linkName,linkPriority,linkMulticastAddress"/>
      <details key="label" value="Link"/>
      <details key="Help" value="com.clovis.cw.help.boot_ioc_node_transport_link"/>
      <details key="initializationFields" value="linkName,link;linkInterface,eth;linkPriority,None;linkMulticastAddress,224.0.1."/>
      <details key="LowerBound" value="1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Link Name"/>
        <details key="pattern" value="^[a-zA-Z][a-zA-Z0-9_]*$"/>
        <details key="message" value="Invalid Link Name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Link Priority"/>
        <details key="pattern" value="^[0]*[1-9][0-9]*$"/>
        <details key="message" value="Link priority cannot be 0 or blank"/>
        <details key="isBlankAllowed" value="false"/>
        <details key="initializationStartIndex" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Link Interface"/>
        <details key="message" value="Invalid link interface"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkMulticastAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Multicast Address"/>
        <details key="pattern" value="^(22[4-9]|23[0-9])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])$"/>
        <details key="message" value="Invalid multicast address"/>
        <details key="initializationStartIndex" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkSupportsChksum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Is Checksum Supported?"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BootConfig">
    <eAnnotations source="CWAnnotation">
      <details key="isHidden" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ioc" lowerBound="1" eType="#//IOC"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Link"/>
      <details key="validator" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.validator.SlotNumberValidator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="IOC Address"/>
        <details key="editor" value="com.clovis.cw.workspace:com.clovis.cw.workspace.dialog.SlotNoComboBoxCellEditor"/>
        <details key="tooltip" value="Manual configuration is to be done only if 'is Multicast Supported' is false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Interface Address"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Transport">
    <eLiterals name="UDP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeInstances">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstance" upperBound="-1"
        eType="#//NodeInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendQueue" lowerBound="1"
        eType="#//Queue" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Send Queue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveQueue" lowerBound="1"
        eType="#//Queue" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Receive Queue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
