REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=sdkguide
DOCTITLE=User Guide
DOCURL=Doc:sdk_$(REL)\/sdkguide
PARTNUMBER=000107
INPUT_WIKI_FORMAT=multipage
OUTPUT_HTML_FORMAT=multipage2

# Makefile for generating html and pdf doc for SDK Guide

include ../tools/Makefile.in

