REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=relnotes
DOCTITLE=Release Notes for Release $(REL)
DOCURL=Doc:sdk_$(REL)\/relnotes
PARTNUMBER=000102
INPUT_WIKI_FORMAT=singlepage
OUTPUT_HTML_FORMAT=multipage1

# Makefile for generating html and pdf doc for Release Notes

include ../tools/Makefile.in
