S7 := 1
include ../mk/preface.mk

all:
	cp -f safplus_watchdog.py $(SAFPLUS_TARGET)/etc
	cp -f asp_linux.py $(SAFPLUS_TARGET)/etc
	cp -f asp_qnx.py $(SAFPLUS_TARGET)/etc
	cp -f safplus.py $(SAFPLUS_TARGET)/etc
	cp -f init.d/safplus $(SAFPLUS_TARGET)/etc/init.d
