#ifndef _CL_AMS_TRIGGER_RMD_H_
#define _CL_AMS_TRIGGER_RMD_H_

#include <clEoApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CL_AMS_TRIGGER_CLNT_ID CL_AMS_ENTITY_TRIGGER_TABLE_ID
#define CL_AMS_TRIGGER_LOAD_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 1)
#define CL_AMS_TRIGGER_LOAD_ALL_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 2)
#define CL_AMS_TRIGGER_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 3)
#define CL_AMS_TRIGGER_ALL_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 4)
#define CL_AMS_TRIGGER_RECOVERY_RESET_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 5)
#define CL_AMS_TRIGGER_RECOVERY_RESET_ALL_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 6)
#define CL_AMS_TRIGGER_RESET_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 7)
#define CL_AMS_TRIGGER_RESET_ALL_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 8)
#define CL_AMS_TRIGGER_GET_METRIC_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 9)
#define CL_AMS_TRIGGER_GET_METRIC_DEFAULT_RMD CL_EO_GET_FULL_FN_NUM(CL_AMS_TRIGGER_CLNT_ID, 10)

extern ClRcT clAmsTriggerRmdInitialize(void);
extern ClRcT clAmsTriggerRmdFinalize(void);

#ifdef __cplusplus
}
#endif

#endif
