/* 
 * File StreamAttributes.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#include "FileFullAction.hxx"
#include "SAFplusLogCommon.hxx"
#include "clMgtContainer.hxx"
#include "clTransaction.hxx"
#include "Replicate.hxx"
#include <string>
#include "clMgtProv.hxx"
#include <cstdint>
#include <vector>
#include "StreamScope.hxx"
#include "StreamAttributes.hxx"


namespace SAFplusLog
  {

    StreamAttributes::StreamAttributes(): SAFplus::MgtContainer("StreamAttributes"), name("name"), fileName("fileName"), replicate("replicate"), fileLocation("fileLocation"), fileUnitSize("fileUnitSize"), recordSize("recordSize"), fileFullAction("fileFullAction"), maximumFilesRotated("maximumFilesRotated"), flushFreq("flushFreq"), flushInterval("flushInterval"), syslog("syslog",false), streamScope("streamScope")
    {
        this->addChildObject(&name, "name");
        this->addChildObject(&fileName, "fileName");
        this->addChildObject(&replicate, "replicate");
        this->addChildObject(&fileLocation, "fileLocation");
        this->addChildObject(&fileUnitSize, "fileUnitSize");
        this->addChildObject(&recordSize, "recordSize");
        this->addChildObject(&fileFullAction, "fileFullAction");
        this->addChildObject(&maximumFilesRotated, "maximumFilesRotated");
        this->addChildObject(&flushFreq, "flushFreq");
        this->addChildObject(&flushInterval, "flushInterval");
        this->addChildObject(&syslog, "syslog");
        this->addChildObject(&streamScope, "streamScope");
        syslog = false;
    };

    std::vector<std::string>* StreamAttributes::getChildNames()
    {
        std::string childNames[] = { "name", "fileName", "replicate", "fileLocation", "fileUnitSize", "recordSize", "fileFullAction", "maximumFilesRotated", "flushFreq", "flushInterval", "syslog", "streamScope" };
        return new std::vector<std::string> (childNames, childNames + sizeof(childNames) / sizeof(childNames[0]));
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/name
     */
    std::string StreamAttributes::getName()
    {
        return this->name;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/name
     */
    void StreamAttributes::setName(std::string nameValue, SAFplus::Transaction &txn)
    {
        this->name = nameValue;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileName
     */
    std::string StreamAttributes::getFileName()
    {
        return this->fileName.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileName
     */
    void StreamAttributes::setFileName(std::string fileNameValue, SAFplus::Transaction &txn)
    {
        this->fileName.set(fileNameValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/replicate
     */
    ::SAFplusLog::Replicate StreamAttributes::getReplicate()
    {
        return this->replicate.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/replicate
     */
    void StreamAttributes::setReplicate(::SAFplusLog::Replicate &replicateValue, SAFplus::Transaction &txn)
    {
        this->replicate.set(replicateValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileLocation
     */
    std::string StreamAttributes::getFileLocation()
    {
        return this->fileLocation.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileLocation
     */
    void StreamAttributes::setFileLocation(std::string fileLocationValue, SAFplus::Transaction &txn)
    {
        this->fileLocation.set(fileLocationValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileUnitSize
     */
    ::uint64_t StreamAttributes::getFileUnitSize()
    {
        return this->fileUnitSize.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileUnitSize
     */
    void StreamAttributes::setFileUnitSize(::uint64_t fileUnitSizeValue, SAFplus::Transaction &txn)
    {
        this->fileUnitSize.set(fileUnitSizeValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/recordSize
     */
    ::uint64_t StreamAttributes::getRecordSize()
    {
        return this->recordSize.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/recordSize
     */
    void StreamAttributes::setRecordSize(::uint64_t recordSizeValue, SAFplus::Transaction &txn)
    {
        this->recordSize.set(recordSizeValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileFullAction
     */
    ::SAFplusLog::FileFullAction StreamAttributes::getFileFullAction()
    {
        return this->fileFullAction.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/fileFullAction
     */
    void StreamAttributes::setFileFullAction(::SAFplusLog::FileFullAction &fileFullActionValue, SAFplus::Transaction &txn)
    {
        this->fileFullAction.set(fileFullActionValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/maximumFilesRotated
     */
    ::uint32_t StreamAttributes::getMaximumFilesRotated()
    {
        return this->maximumFilesRotated.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/maximumFilesRotated
     */
    void StreamAttributes::setMaximumFilesRotated(::uint32_t maximumFilesRotatedValue, SAFplus::Transaction &txn)
    {
        this->maximumFilesRotated.set(maximumFilesRotatedValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/flushFreq
     */
    ::uint32_t StreamAttributes::getFlushFreq()
    {
        return this->flushFreq.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/flushFreq
     */
    void StreamAttributes::setFlushFreq(::uint32_t flushFreqValue, SAFplus::Transaction &txn)
    {
        this->flushFreq.set(flushFreqValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/flushInterval
     */
    ::uint64_t StreamAttributes::getFlushInterval()
    {
        return this->flushInterval.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/flushInterval
     */
    void StreamAttributes::setFlushInterval(::uint64_t flushIntervalValue, SAFplus::Transaction &txn)
    {
        this->flushInterval.set(flushIntervalValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/syslog
     */
    bool StreamAttributes::getSyslog()
    {
        return this->syslog.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/syslog
     */
    void StreamAttributes::setSyslog(bool syslogValue, SAFplus::Transaction &txn)
    {
        this->syslog.set(syslogValue,txn);
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/streamScope
     */
    ::SAFplusLog::StreamScope StreamAttributes::getStreamScope()
    {
        return this->streamScope.value;
    };

    /*
     * XPATH: /SAFplusLog/StreamAttributes/streamScope
     */
    void StreamAttributes::setStreamScope(::SAFplusLog::StreamScope &streamScopeValue, SAFplus::Transaction &txn)
    {
        this->streamScope.set(streamScopeValue,txn);
    };

    StreamAttributes::~StreamAttributes()
    {
    };

}
/* namespace ::SAFplusLog */
