#!/usr/bin/python
import time, os, sys
count = 0
pid = os.getpid()
arg = sys.argv[0]
if len(sys.argv) > 1:
  arg = sys.argv[1]
while 1:
  print time.asctime(), "%s.%d: non-SAF-aware application running for %d seconds" % (arg,pid, count)
  time.sleep(5)
  count += 5
