REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=installguide
DOCTITLE=Installation Guide
DOCURL=Doc:sdk_$(REL)\/installguide
PARTNUMBER=000101
INPUT_WIKI_FORMAT=singlepage
OUTPUT_HTML_FORMAT=multipage1

# Makefile for generating html and pdf doc for Installation Guide

include ../tools/Makefile.in
