/*
 * Copyright (C) 2002-2012 OpenClovis Solutions Inc.  All Rights Reserved.
 *
 * This file is available  under  a  commercial  license  from  the
 * copyright  holder or the GNU General Public License Version 2.0.
 * 
 * The source code for  this program is not published  or otherwise 
 * divested of  its trade secrets, irrespective  of  what  has been 
 * deposited with the U.S. Copyright office.
 * 
 * This program is distributed in the  hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * For more  information, see  the file  COPYING provided with this
 * material.
 */


/*********************************************************************
* ModuleName  : idl
*********************************************************************/
/*********************************************************************
* Description : This file contains the declarations for marshall 
*               and unmarshall funtions of ClCorMsoConfigIDLT 
*     
* THIS FILE IS AUTO-GENERATED BY OPENCLOVIS IDE. EDIT THIS FILE AT
* YOUR OWN RISK. ANY CHANGE TO THIS FILE WILL BE OVERWRITTEN ON
* RE-GENERATION.
*     
*********************************************************************/

#ifndef _XDR_CL_COR_MSO_CONFIG_IDLT_H_
#define _XDR_CL_COR_MSO_CONFIG_IDLT_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "clXdrApi.h"

#include "clCorTxnJobStream.h"
#include "clTimerApi.h"
#include "clCorNotifyApi.h"
#include "clCorClient.h"
#include "clIocApi.h"
#include "clCorDmData.h"
#include "clCorMetaData.h"
#include "clCorSync.h"
#include "xdrClCorMsoConfigOpIDLT.h"
#include "xdrClIocPhysicalAddressT.h"
#include "xdrClCorAlarmConfiguredDataIDLT.h"

struct _ClCorMsoConfigIDLT_4_1_0;

typedef struct _ClCorMsoConfigIDLT_4_1_0 {
    ClVersionT    version;
    ClCorMsoConfigOpIDLT_4_0_0    msoConfigOp;
    ClNameT    compName;
    ClIocPhysicalAddressT_4_0_0    compAddr;
    ClCorAlarmConfiguredDataIDLT_4_1_0    alarmInfo;

}ClCorMsoConfigIDLT_4_1_0;


ClRcT  clXdrMarshallClCorMsoConfigIDLT_4_1_0(void *,ClBufferHandleT , ClUint32T);

ClRcT  clXdrUnmarshallClCorMsoConfigIDLT_4_1_0(ClBufferHandleT, void *);

#define clXdrMarshallArrayClCorMsoConfigIDLT_4_1_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallArray((pointer), sizeof(ClCorMsoConfigIDLT_4_1_0), (multiplicity), clXdrMarshallClCorMsoConfigIDLT_4_1_0, (msg), (isDelete))

#define clXdrUnmarshallArrayClCorMsoConfigIDLT_4_1_0(msg,pointer, multiplicity) \
clXdrUnmarshallArray((msg),(pointer), sizeof(ClCorMsoConfigIDLT_4_1_0), (multiplicity), clXdrUnmarshallClCorMsoConfigIDLT_4_1_0)

#define clXdrMarshallPointerClCorMsoConfigIDLT_4_1_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallPointer((pointer), sizeof(ClCorMsoConfigIDLT_4_1_0), (multiplicity), clXdrMarshallClCorMsoConfigIDLT_4_1_0, (msg), (isDelete))

#define clXdrUnmarshallPointerClCorMsoConfigIDLT_4_1_0(msg,pointer) \
clXdrUnmarshallPointer((msg),(pointer), sizeof(ClCorMsoConfigIDLT_4_1_0), clXdrUnmarshallClCorMsoConfigIDLT_4_1_0)

#define clXdrMarshallPtrClCorMsoConfigIDLT_4_1_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallPtr((pointer), sizeof(ClCorMsoConfigIDLT_4_1_0), (multiplicity), clXdrMarshallClCorMsoConfigIDLT_4_1_0, (msg), (isDelete))

#define clXdrUnmarshallPtrClCorMsoConfigIDLT_4_1_0(msg,pointer,multiplicity) \
clXdrUnmarshallPtr((msg),(pointer), sizeof(ClCorMsoConfigIDLT_4_1_0),multiplicity, clXdrUnmarshallClCorMsoConfigIDLT_4_1_0)



#ifdef __cplusplus
}
#endif

#endif /*_XDR_CL_COR_MSO_CONFIG_IDLT_H_*/
