/*
 * Copyright (C) 2002-2012 OpenClovis Solutions Inc.  All Rights Reserved.
 *
 * This file is available  under  a  commercial  license  from  the
 * copyright  holder or the GNU General Public License Version 2.0.
 * 
 * The source code for  this program is not published  or otherwise 
 * divested of  its trade secrets, irrespective  of  what  has been 
 * deposited with the U.S. Copyright office.
 * 
 * This program is distributed in the  hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * For more  information, see  the file  COPYING provided with this
 * material.
 */

/*********************************************************************
* ModuleName  : idl
*********************************************************************/
/*********************************************************************
* Description : Unmarshall routine for ClAlarmUtilPayLoadT
*     
* THIS FILE IS AUTO-GENERATED BY OPENCLOVIS IDE. EDIT THIS FILE AT
* YOUR OWN RISK. ANY CHANGE TO THIS FILE WILL BE OVERWRITTEN ON
* RE-GENERATION.
*     
*********************************************************************/
#include "xdrClAlarmUtilPayLoadT.h"

ClRcT clXdrUnmarshallClAlarmUtilPayLoadT(ClBufferHandleT msg , void* pGenVar)
{
    ClAlarmUtilPayLoadT* pVar = (ClAlarmUtilPayLoadT*)pGenVar;
    ClRcT rc;

    if ((void*)0 == pVar)
    {
        return CL_XDR_RC(CL_ERR_NULL_POINTER);
    }


    rc = clXdrUnmarshallPtrClCorMOIdT_4_0_0(msg,(void**)&(pVar->pMoId),1);
    if (CL_OK != rc)
    {
        return rc;
    }

    rc = clXdrUnmarshallClUint32T(msg,&(pVar->numTlvs));
    if (CL_OK != rc)
    {
        return rc;
    }

    rc = clXdrUnmarshallPtrClAlarmUtilTlvT(msg,(void**)&(pVar->pTlv),pVar->numTlvs);
    if (CL_OK != rc)
    {
        return rc;
    }


    return rc;
}

