#ifndef _CL_SNMP_SAFAMF_ENUMS_H
#define _CL_SNMP_SAFAMF_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

/* enums for column saAmfApplicationAdminState */
#define SAAMFAPPLICATIONADMINSTATE_UNLOCKED        1
#define SAAMFAPPLICATIONADMINSTATE_LOCKED        2
#define SAAMFAPPLICATIONADMINSTATE_LOCKEDINSTANTIATION        3
#define SAAMFAPPLICATIONADMINSTATE_SHUTTINGDOWN        4

/* enums for column saAmfApplicationAdminStateTrigger */
#define SAAMFAPPLICATIONADMINSTATETRIGGER_STABLE        0
#define SAAMFAPPLICATIONADMINSTATETRIGGER_UNLOCK        1
#define SAAMFAPPLICATIONADMINSTATETRIGGER_LOCK        2
#define SAAMFAPPLICATIONADMINSTATETRIGGER_LOCKINSTANTIATION        3
#define SAAMFAPPLICATIONADMINSTATETRIGGER_UNLOCKINSTANTIATION        4
#define SAAMFAPPLICATIONADMINSTATETRIGGER_SHUTDOWN        5

/* enums for column saAmfApplicationRestartState */
#define SAAMFAPPLICATIONRESTARTSTATE_STABLE        0
#define SAAMFAPPLICATIONRESTARTSTATE_RESTARTING        1

/* enums for column saAmfApplicationRowStatus */
#define SAAMFAPPLICATIONROWSTATUS_ACTIVE        1
#define SAAMFAPPLICATIONROWSTATUS_NOTINSERVICE        2
#define SAAMFAPPLICATIONROWSTATUS_NOTREADY        3
#define SAAMFAPPLICATIONROWSTATUS_CREATEANDGO        4
#define SAAMFAPPLICATIONROWSTATUS_CREATEANDWAIT        5
#define SAAMFAPPLICATIONROWSTATUS_DESTROY        6

/* enums for column saAmfNodeAdminState */
#define SAAMFNODEADMINSTATE_UNLOCKED        1
#define SAAMFNODEADMINSTATE_LOCKED        2
#define SAAMFNODEADMINSTATE_LOCKEDINSTANTIATION        3
#define SAAMFNODEADMINSTATE_SHUTTINGDOWN        4

/* enums for column saAmfNodeOperationalState */
#define SAAMFNODEOPERATIONALSTATE_ENABLED        1
#define SAAMFNODEOPERATIONALSTATE_DISABLED        2

/* enums for column saAmfNodeAutoRepairOption */
#define SAAMFNODEAUTOREPAIROPTION_TRUE        1
#define SAAMFNODEAUTOREPAIROPTION_FALSE        2

/* enums for column saAmfNodeRebootOnTerminationFail */
#define SAAMFNODEREBOOTONTERMINATIONFAIL_TRUE        1
#define SAAMFNODEREBOOTONTERMINATIONFAIL_FALSE        2

/* enums for column saAmfNodeRebootOnInstantiationFail */
#define SAAMFNODEREBOOTONINSTANTIATIONFAIL_TRUE        1
#define SAAMFNODEREBOOTONINSTANTIATIONFAIL_FALSE        2

/* enums for column saAmfNodeAdminStateTrigger */
#define SAAMFNODEADMINSTATETRIGGER_STABLE        0
#define SAAMFNODEADMINSTATETRIGGER_UNLOCK        1
#define SAAMFNODEADMINSTATETRIGGER_LOCK        2
#define SAAMFNODEADMINSTATETRIGGER_LOCKINSTANTIATION        3
#define SAAMFNODEADMINSTATETRIGGER_UNLOCKINSTANTIATION        4
#define SAAMFNODEADMINSTATETRIGGER_SHUTDOWN        5

/* enums for column saAmfNodeRestartState */
#define SAAMFNODERESTARTSTATE_STABLE        0
#define SAAMFNODERESTARTSTATE_RESTARTING        1

/* enums for column saAmfNodeRepair */
#define SAAMFNODEREPAIR_STABLE        0
#define SAAMFNODEREPAIR_REPAIRING        1

/* enums for column saAmfNodeRowStatus */
#define SAAMFNODEROWSTATUS_ACTIVE        1
#define SAAMFNODEROWSTATUS_NOTINSERVICE        2
#define SAAMFNODEROWSTATUS_NOTREADY        3
#define SAAMFNODEROWSTATUS_CREATEANDGO        4
#define SAAMFNODEROWSTATUS_CREATEANDWAIT        5
#define SAAMFNODEROWSTATUS_DESTROY        6

/* enums for column saAmfSGRedModel */
#define SAAMFSGREDMODEL_TWON        1
#define SAAMFSGREDMODEL_NPLUSM        2
#define SAAMFSGREDMODEL_NWAY        3
#define SAAMFSGREDMODEL_NWAYACTIVE        4
#define SAAMFSGREDMODEL_NOREDUNDANCY        5

/* enums for column saAmfSGAdminState */
#define SAAMFSGADMINSTATE_UNLOCKED        1
#define SAAMFSGADMINSTATE_LOCKED        2
#define SAAMFSGADMINSTATE_LOCKEDINSTANTIATION        3
#define SAAMFSGADMINSTATE_SHUTTINGDOWN        4

/* enums for column saAmfSGAutoRepairOption */
#define SAAMFSGAUTOREPAIROPTION_TRUE        1
#define SAAMFSGAUTOREPAIROPTION_FALSE        2

/* enums for column saAmfSGAutoAdjustOption */
#define SAAMFSGAUTOADJUSTOPTION_TRUE        1
#define SAAMFSGAUTOADJUSTOPTION_FALSE        2

/* enums for column saAmfSGAdjustState */
#define SAAMFSGADJUSTSTATE_STABLE        0
#define SAAMFSGADJUSTSTATE_ADJUSTING        1

/* enums for column saAmfSGAdminStateTrigger */
#define SAAMFSGADMINSTATETRIGGER_STABLE        0
#define SAAMFSGADMINSTATETRIGGER_UNLOCK        1
#define SAAMFSGADMINSTATETRIGGER_LOCK        2
#define SAAMFSGADMINSTATETRIGGER_LOCKINSTANTIATION        3
#define SAAMFSGADMINSTATETRIGGER_UNLOCKINSTANTIATION        4
#define SAAMFSGADMINSTATETRIGGER_SHUTDOWN        5

/* enums for column saAmfSGRowStatus */
#define SAAMFSGROWSTATUS_ACTIVE        1
#define SAAMFSGROWSTATUS_NOTINSERVICE        2
#define SAAMFSGROWSTATUS_NOTREADY        3
#define SAAMFSGROWSTATUS_CREATEANDGO        4
#define SAAMFSGROWSTATUS_CREATEANDWAIT        5
#define SAAMFSGROWSTATUS_DESTROY        6

/* enums for column saAmfSUAdminState */
#define SAAMFSUADMINSTATE_UNLOCKED        1
#define SAAMFSUADMINSTATE_LOCKED        2
#define SAAMFSUADMINSTATE_LOCKEDINSTANTIATION        3
#define SAAMFSUADMINSTATE_SHUTTINGDOWN        4

/* enums for column saAmfSUFailOver */
#define SAAMFSUFAILOVER_TRUE        1
#define SAAMFSUFAILOVER_FALSE        2

/* enums for column saAmfSUReadinessState */
#define SAAMFSUREADINESSSTATE_OUTOFSERVICE        1
#define SAAMFSUREADINESSSTATE_INSERVICE        2
#define SAAMFSUREADINESSSTATE_STOPPING        3

/* enums for column saAmfSUOperState */
#define SAAMFSUOPERSTATE_ENABLED        1
#define SAAMFSUOPERSTATE_DISABLED        2

/* enums for column saAmfSUPresenceState */
#define SAAMFSUPRESENCESTATE_SAAMFUNINSTANTIATED        1
#define SAAMFSUPRESENCESTATE_SAAMFINSTANTIATING        2
#define SAAMFSUPRESENCESTATE_SAAMFINSTANTIATED        3
#define SAAMFSUPRESENCESTATE_SAAMFTERMINATING        4
#define SAAMFSUPRESENCESTATE_SAAMFRESTARTING        5
#define SAAMFSUPRESENCESTATE_SAAMFINSTANTIATIONFAILED        6
#define SAAMFSUPRESENCESTATE_SAAMFTERMINATIONFAILED        7

/* enums for column saAmfSUPreInstantiable */
#define SAAMFSUPREINSTANTIABLE_TRUE        1
#define SAAMFSUPREINSTANTIABLE_FALSE        2

/* enums for column saAmfSUIsExternal */
#define SAAMFSUISEXTERNAL_TRUE        1
#define SAAMFSUISEXTERNAL_FALSE        2

/* enums for column saAmfSUAdminStateTrigger */
#define SAAMFSUADMINSTATETRIGGER_STABLE        0
#define SAAMFSUADMINSTATETRIGGER_UNLOCK        1
#define SAAMFSUADMINSTATETRIGGER_LOCK        2
#define SAAMFSUADMINSTATETRIGGER_LOCKINSTANTIATION        3
#define SAAMFSUADMINSTATETRIGGER_UNLOCKINSTANTIATION        4
#define SAAMFSUADMINSTATETRIGGER_SHUTDOWN        5

/* enums for column saAmfSURestartState */
#define SAAMFSURESTARTSTATE_STABLE        0
#define SAAMFSURESTARTSTATE_RESTARTING        1

/* enums for column saAmfSUEamTrigger */
#define SAAMFSUEAMTRIGGER_START        1
#define SAAMFSUEAMTRIGGER_STOP        2

/* enums for column saAmfSURepair */
#define SAAMFSUREPAIR_STABLE        0
#define SAAMFSUREPAIR_REPAIRING        1

/* enums for column saAmfSURowStatus */
#define SAAMFSUROWSTATUS_ACTIVE        1
#define SAAMFSUROWSTATUS_NOTINSERVICE        2
#define SAAMFSUROWSTATUS_NOTREADY        3
#define SAAMFSUROWSTATUS_CREATEANDGO        4
#define SAAMFSUROWSTATUS_CREATEANDWAIT        5
#define SAAMFSUROWSTATUS_DESTROY        6

/* enums for column saAmfSIAdminState */
#define SAAMFSIADMINSTATE_UNLOCKED        1
#define SAAMFSIADMINSTATE_LOCKED        2
#define SAAMFSIADMINSTATE_SHUTTINGDOWN        4

/* enums for column saAmfSIAssignmentState */
#define SAAMFSIASSIGNMENTSTATE_UNASSIGNED        1
#define SAAMFSIASSIGNMENTSTATE_FULLYASSIGNED        2
#define SAAMFSIASSIGNMENTSTATE_PARTIALLYASSIGNED        3

/* enums for column saAmfSIAdminStateTrigger */
#define SAAMFSIADMINSTATETRIGGER_STABLE        0
#define SAAMFSIADMINSTATETRIGGER_UNLOCK        1
#define SAAMFSIADMINSTATETRIGGER_LOCK        2
#define SAAMFSIADMINSTATETRIGGER_SHUTDOWN        5

/* enums for column saAmfSISwapState */
#define SAAMFSISWAPSTATE_STABLE        0
#define SAAMFSISWAPSTATE_SWAPPING        1

/* enums for column saAmfSIRowStatus */
#define SAAMFSIROWSTATUS_ACTIVE        1
#define SAAMFSIROWSTATUS_NOTINSERVICE        2
#define SAAMFSIROWSTATUS_NOTREADY        3
#define SAAMFSIROWSTATUS_CREATEANDGO        4
#define SAAMFSIROWSTATUS_CREATEANDWAIT        5
#define SAAMFSIROWSTATUS_DESTROY        6

/* enums for column saAmfSUsperSIRowStatus */
#define SAAMFSUSPERSIROWSTATUS_ACTIVE        1
#define SAAMFSUSPERSIROWSTATUS_NOTINSERVICE        2
#define SAAMFSUSPERSIROWSTATUS_NOTREADY        3
#define SAAMFSUSPERSIROWSTATUS_CREATEANDGO        4
#define SAAMFSUSPERSIROWSTATUS_CREATEANDWAIT        5
#define SAAMFSUSPERSIROWSTATUS_DESTROY        6

/* enums for column saAmfSISIDepRowStatus */
#define SAAMFSISIDEPROWSTATUS_ACTIVE        1
#define SAAMFSISIDEPROWSTATUS_NOTINSERVICE        2
#define SAAMFSISIDEPROWSTATUS_NOTREADY        3
#define SAAMFSISIDEPROWSTATUS_CREATEANDGO        4
#define SAAMFSISIDEPROWSTATUS_CREATEANDWAIT        5
#define SAAMFSISIDEPROWSTATUS_DESTROY        6

/* enums for column saAmfCompCapability */
#define SAAMFCOMPCAPABILITY_XACTIVEANDYSTANDBY        1
#define SAAMFCOMPCAPABILITY_XACTIVEORYSTANDBY        2
#define SAAMFCOMPCAPABILITY_ONEACTIVEORXSTANDBY        3
#define SAAMFCOMPCAPABILITY_ONEACTIVEORONESTANDBY        4
#define SAAMFCOMPCAPABILITY_XACTIVE        5
#define SAAMFCOMPCAPABILITY_ONEACTIVE        6
#define SAAMFCOMPCAPABILITY_NONPREINSTANTIABLE        7

/* enums for column saAmfCompCategory */
#define SAAMFCOMPCATEGORY_SAAWARE        0
#define SAAMFCOMPCATEGORY_PROXIEDLOCALPREINSTANTIABLE        1
#define SAAMFCOMPCATEGORY_PROXIEDLOCALNONPREINSTANTIABLE        2
#define SAAMFCOMPCATEGORY_EXTERNALPREINSTANTIABLE        3
#define SAAMFCOMPCATEGORY_EXTERNALNONPREINSTANTIABLE        4
#define SAAMFCOMPCATEGORY_UNPROXIEDNONSAAWARE        5

/* enums for column saAmfCompRecoveryOnError */
#define SAAMFCOMPRECOVERYONERROR_NONE        1
#define SAAMFCOMPRECOVERYONERROR_COMPONENTRESTART        2
#define SAAMFCOMPRECOVERYONERROR_COMPONENTFAILOVER        3
#define SAAMFCOMPRECOVERYONERROR_NODESWITCHOVER        4
#define SAAMFCOMPRECOVERYONERROR_NODEFAILOVER        5
#define SAAMFCOMPRECOVERYONERROR_NODEFAILFAST        6
#define SAAMFCOMPRECOVERYONERROR_CLUSTERRESET        7
#define SAAMFCOMPRECOVERYONERROR_APPLICATIONRESTART        8

/* enums for column saAmfCompDisableRestart */
#define SAAMFCOMPDISABLERESTART_TRUE        1
#define SAAMFCOMPDISABLERESTART_FALSE        2

/* enums for column saAmfCompOperState */
#define SAAMFCOMPOPERSTATE_ENABLED        1
#define SAAMFCOMPOPERSTATE_DISABLED        2

/* enums for column saAmfCompPresenceState */
#define SAAMFCOMPPRESENCESTATE_SAAMFUNINSTANTIATED        1
#define SAAMFCOMPPRESENCESTATE_SAAMFINSTANTIATING        2
#define SAAMFCOMPPRESENCESTATE_SAAMFINSTANTIATED        3
#define SAAMFCOMPPRESENCESTATE_SAAMFTERMINATING        4
#define SAAMFCOMPPRESENCESTATE_SAAMFRESTARTING        5
#define SAAMFCOMPPRESENCESTATE_SAAMFINSTANTIATIONFAILED        6
#define SAAMFCOMPPRESENCESTATE_SAAMFTERMINATIONFAILED        7

/* enums for column saAmfCompReadinessState */
#define SAAMFCOMPREADINESSSTATE_OUTOFSERVICE        1
#define SAAMFCOMPREADINESSSTATE_INSERVICE        2
#define SAAMFCOMPREADINESSSTATE_STOPPING        3

/* enums for column saAmfCompRestartState */
#define SAAMFCOMPRESTARTSTATE_STABLE        0
#define SAAMFCOMPRESTARTSTATE_RESTARTING        1

/* enums for column saAmfCompEamTrigger */
#define SAAMFCOMPEAMTRIGGER_START        1
#define SAAMFCOMPEAMTRIGGER_STOP        2

/* enums for column saAmfCompRowStatus */
#define SAAMFCOMPROWSTATUS_ACTIVE        1
#define SAAMFCOMPROWSTATUS_NOTINSERVICE        2
#define SAAMFCOMPROWSTATUS_NOTREADY        3
#define SAAMFCOMPROWSTATUS_CREATEANDGO        4
#define SAAMFCOMPROWSTATUS_CREATEANDWAIT        5
#define SAAMFCOMPROWSTATUS_DESTROY        6

/* enums for column saAmfCompCSTypeSupportedRowStatus */
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_ACTIVE        1
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_NOTINSERVICE        2
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_NOTREADY        3
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_CREATEANDGO        4
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_CREATEANDWAIT        5
#define SAAMFCOMPCSTYPESUPPORTEDROWSTATUS_DESTROY        6

/* enums for column saAmfCSIRowStatus */
#define SAAMFCSIROWSTATUS_ACTIVE        1
#define SAAMFCSIROWSTATUS_NOTINSERVICE        2
#define SAAMFCSIROWSTATUS_NOTREADY        3
#define SAAMFCSIROWSTATUS_CREATEANDGO        4
#define SAAMFCSIROWSTATUS_CREATEANDWAIT        5
#define SAAMFCSIROWSTATUS_DESTROY        6

/* enums for column saAmfCSICSIDepRowStatus */
#define SAAMFCSICSIDEPROWSTATUS_ACTIVE        1
#define SAAMFCSICSIDEPROWSTATUS_NOTINSERVICE        2
#define SAAMFCSICSIDEPROWSTATUS_NOTREADY        3
#define SAAMFCSICSIDEPROWSTATUS_CREATEANDGO        4
#define SAAMFCSICSIDEPROWSTATUS_CREATEANDWAIT        5
#define SAAMFCSICSIDEPROWSTATUS_DESTROY        6

/* enums for column saAmfCSINameValueRowStatus */
#define SAAMFCSINAMEVALUEROWSTATUS_ACTIVE        1
#define SAAMFCSINAMEVALUEROWSTATUS_NOTINSERVICE        2
#define SAAMFCSINAMEVALUEROWSTATUS_NOTREADY        3
#define SAAMFCSINAMEVALUEROWSTATUS_CREATEANDGO        4
#define SAAMFCSINAMEVALUEROWSTATUS_CREATEANDWAIT        5
#define SAAMFCSINAMEVALUEROWSTATUS_DESTROY        6

/* enums for column saAmfCSTypeAttrRowStatus */
#define SAAMFCSTYPEATTRROWSTATUS_ACTIVE        1
#define SAAMFCSTYPEATTRROWSTATUS_NOTINSERVICE        2
#define SAAMFCSTYPEATTRROWSTATUS_NOTREADY        3
#define SAAMFCSTYPEATTRROWSTATUS_CREATEANDGO        4
#define SAAMFCSTYPEATTRROWSTATUS_CREATEANDWAIT        5
#define SAAMFCSTYPEATTRROWSTATUS_DESTROY        6

/* enums for column saAmfSUSIHAState */
#define SAAMFSUSIHASTATE_ACTIVE        1
#define SAAMFSUSIHASTATE_STANDBY        2
#define SAAMFSUSIHASTATE_QUIESCED        3
#define SAAMFSUSIHASTATE_QUIESCING        4

/* enums for column saAmfHealthCheckRowStatus */
#define SAAMFHEALTHCHECKROWSTATUS_ACTIVE        1
#define SAAMFHEALTHCHECKROWSTATUS_NOTINSERVICE        2
#define SAAMFHEALTHCHECKROWSTATUS_NOTREADY        3
#define SAAMFHEALTHCHECKROWSTATUS_CREATEANDGO        4
#define SAAMFHEALTHCHECKROWSTATUS_CREATEANDWAIT        5
#define SAAMFHEALTHCHECKROWSTATUS_DESTROY        6

/* enums for column saAmfSCompCsiHAState */
#define SAAMFSCOMPCSIHASTATE_ACTIVE        1
#define SAAMFSCOMPCSIHASTATE_STANDBY        2
#define SAAMFSCOMPCSIHASTATE_QUIESCED        3
#define SAAMFSCOMPCSIHASTATE_QUIESCING        4


/* enums for scalar saAmfServiceStartEnabled */
#define SAAMFSERVICESTARTENABLED_TRUE        1
#define SAAMFSERVICESTARTENABLED_FALSE        2

/* enums for scalar saAmfServiceState */
#define SAAMFSERVICESTATE_RUNNING        1
#define SAAMFSERVICESTATE_STOPPED        2
#define SAAMFSERVICESTATE_STARTINGUP        3
#define SAAMFSERVICESTATE_SHUTTINGDOWN        4
#define SAAMFSERVICESTATE_UNAVAILABLE        5

/* enums for scalar saAmfClusterAdminState */
#define SAAMFCLUSTERADMINSTATE_UNLOCKED        1
#define SAAMFCLUSTERADMINSTATE_LOCKED        2
#define SAAMFCLUSTERADMINSTATE_LOCKEDINSTANTIATION        3
#define SAAMFCLUSTERADMINSTATE_SHUTTINGDOWN        4

/* enums for scalar saAmfClusterAdminStateTrigger */
#define SAAMFCLUSTERADMINSTATETRIGGER_STABLE        0
#define SAAMFCLUSTERADMINSTATETRIGGER_UNLOCK        1
#define SAAMFCLUSTERADMINSTATETRIGGER_LOCK        2
#define SAAMFCLUSTERADMINSTATETRIGGER_LOCKINSTANTIATION        3
#define SAAMFCLUSTERADMINSTATETRIGGER_UNLOCKINSTANTIATION        4
#define SAAMFCLUSTERADMINSTATETRIGGER_SHUTDOWN        5

/* enums for scalar saAmfProbableCause */
#define SAAMFPROBABLECAUSE_ADAPTERERROR        1
#define SAAMFPROBABLECAUSE_APPLICATIONSUBSYSTEMFAILURE        2
#define SAAMFPROBABLECAUSE_BANDWIDTHREDUCED        3
#define SAAMFPROBABLECAUSE_CALLESTABLISHMENTERROR        4
#define SAAMFPROBABLECAUSE_COMMUNICATIONSPROTOCOLERROR        5
#define SAAMFPROBABLECAUSE_COMMUNICATIONSSUBSYSTEMFAILURE        6
#define SAAMFPROBABLECAUSE_CONFIGURATIONORCUSTOMIZATIONERROR        7
#define SAAMFPROBABLECAUSE_CONGESTION        8
#define SAAMFPROBABLECAUSE_CORRUPTDATA        9
#define SAAMFPROBABLECAUSE_CPUCYCLESLIMITEXCEEDED        10
#define SAAMFPROBABLECAUSE_DATASETORMODEMERROR        11
#define SAAMFPROBABLECAUSE_DEGRADEDSIGNAL        12
#define SAAMFPROBABLECAUSE_DTE        13
#define SAAMFPROBABLECAUSE_ENCLOSUREDOOROPEN        14
#define SAAMFPROBABLECAUSE_EQUIPMENTMALFUNCTION        15
#define SAAMFPROBABLECAUSE_EXCESSIVEVIBRATION        16
#define SAAMFPROBABLECAUSE_FILEERROR        17
#define SAAMFPROBABLECAUSE_FIREDETECTED        18
#define SAAMFPROBABLECAUSE_FLOODDETECTED        19
#define SAAMFPROBABLECAUSE_FRAMINGERROR        20
#define SAAMFPROBABLECAUSE_HEATINGORVENTILATIONORCOOLINGSYSTEMPROBLEM        21
#define SAAMFPROBABLECAUSE_HUMIDITYUNACCEPTABLE        22
#define SAAMFPROBABLECAUSE_INPUTOUTPUTDEVICEERROR        23
#define SAAMFPROBABLECAUSE_INPUTDEVICEERROR        24
#define SAAMFPROBABLECAUSE_LANERROR        25
#define SAAMFPROBABLECAUSE_LEAKDETECTED        26
#define SAAMFPROBABLECAUSE_LOCALNODETRANSMISSIONERROR        27
#define SAAMFPROBABLECAUSE_LOSSOFFRAME        28
#define SAAMFPROBABLECAUSE_LOSSOFSIGNAL        29
#define SAAMFPROBABLECAUSE_MATERIALSUPPLYEXHAUSTED        30
#define SAAMFPROBABLECAUSE_MULTIPLEXERPROBLEM        31
#define SAAMFPROBABLECAUSE_OUTOFMEMORY        32
#define SAAMFPROBABLECAUSE_OUTPUTDEVICEERROR        33
#define SAAMFPROBABLECAUSE_PERFORMANCEDEGRADED        34
#define SAAMFPROBABLECAUSE_POWERPROBLEM        35
#define SAAMFPROBABLECAUSE_PRESSUREUNACCEPTABLE        36
#define SAAMFPROBABLECAUSE_PROCESSORPROBLEM        37
#define SAAMFPROBABLECAUSE_PUMPFAILURE        38
#define SAAMFPROBABLECAUSE_QUEUESIZEEXCEEDED        39
#define SAAMFPROBABLECAUSE_RECEIVEFAILURE        40
#define SAAMFPROBABLECAUSE_RECEIVERFAILURE        41
#define SAAMFPROBABLECAUSE_REMOTENODETRANSMISSIONERROR        42
#define SAAMFPROBABLECAUSE_RESOURCEATORNEARINGCAPACITY        43
#define SAAMFPROBABLECAUSE_RESPONSETIMEEXCESSIVE        44
#define SAAMFPROBABLECAUSE_RETRANSMISSIONRATEEXCESSIVE        45
#define SAAMFPROBABLECAUSE_SOFWAREERROR        46
#define SAAMFPROBABLECAUSE_SOFWAREPROGRAMABNORMALLYTERMINATED        47
#define SAAMFPROBABLECAUSE_SOFTWAREPROGRAMERROR        48
#define SAAMFPROBABLECAUSE_STORAGECAPACITYPROBLEM        49
#define SAAMFPROBABLECAUSE_TEMPERATUREUNACCEPTABLE        50
#define SAAMFPROBABLECAUSE_THRESHOLDCROSSED        51
#define SAAMFPROBABLECAUSE_TIMINGPROBLEM        52
#define SAAMFPROBABLECAUSE_TOXICLEAKDETECTED        53
#define SAAMFPROBABLECAUSE_TRANSMITFAILURE        54
#define SAAMFPROBABLECAUSE_TRANSMITTERFAILURE        55
#define SAAMFPROBABLECAUSE_UNDERLYINGRESOURCEUNAVAILABLE        56
#define SAAMFPROBABLECAUSE_VERSIONMISMATCH        57
#define SAAMFPROBABLECAUSE_AUTHENTICATIONFAILURE        58
#define SAAMFPROBABLECAUSE_BREACHOFCONFIDENTIALITY        59
#define SAAMFPROBABLECAUSE_CABLETAMPER        60
#define SAAMFPROBABLECAUSE_DELAYEDINFORMATION        61
#define SAAMFPROBABLECAUSE_DENIALOFSERVICE        62
#define SAAMFPROBABLECAUSE_DUPLICATEINFORMATION        63
#define SAAMFPROBABLECAUSE_INFORMATIONMISSING        64
#define SAAMFPROBABLECAUSE_INFORMATIONMODIFICATIONDETECTED        65
#define SAAMFPROBABLECAUSE_INFORMATIONOUTOFSEQUENCE        66
#define SAAMFPROBABLECAUSE_INTRUSIONDETECTION        67
#define SAAMFPROBABLECAUSE_KEYEXPIRED        68
#define SAAMFPROBABLECAUSE_NONREPUDIATIONFAILURE        69
#define SAAMFPROBABLECAUSE_OUTOFHOURSACTIVITY        70
#define SAAMFPROBABLECAUSE_OUTOFSERVICE        71
#define SAAMFPROBABLECAUSE_PROCEDURALERROR        72
#define SAAMFPROBABLECAUSE_UNAUTHORIZEDACCESSATTEMPT        73
#define SAAMFPROBABLECAUSE_UNEXPECTEDINFORMATION        74
#define SAAMFPROBABLECAUSE_UNSPECIFIEDREASON        75

#ifdef __cplusplus
}
#endif

#endif /* _CL_SNMP_SAFAMF_ENUMS_H */
