#!/bin/bash
export SAFPLUS_BACKPLANE_INTERFACE=eth0
export SAFPLUS_MSG_TRANSPORT=clMsgUdp.so
export LD_LIBRARY_PATH=`pwd`/lib:`pwd`/plugin:$LD_LIBRARY_PATH
export PYTHONPATH=`pwd`/lib:`pwd`/bin:`pwd`/test:$PYTHONPATH

bin/safplus_cleanup
