#!/bin/bash
###############################################################################
#
# Copyright (C) 2002-2009 by OpenClovis Inc. All  Rights Reserved.
# 
# The source code for  this program is not published  or otherwise 
# divested of  its trade secrets, irrespective  of  what  has been 
# deposited with the U.S. Copyright office.
# 
# This program is  free software; you can redistribute it and / or
# modify  it under  the  terms  of  the GNU General Public License
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the  hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
# 
# You  should  have  received  a  copy of  the  GNU General Public
# License along  with  this program. If  not,  write  to  the 
# Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
###############################################################################

OS=`uname`
echo "## Start of Nodeinfo =================================================="
echo "## Host Info:"
echo "hostid          : `hostid`"
echo "hostname        : `hostname`"

echo "## CPU Info:"
if [ $OS == 'SunOS' ]
then
   psrinfo -v
else
   cat /proc/cpuinfo
fi

echo "## Kernel Info:"
echo "uname           : `uname -a`"
echo "cmdline         : `cat /proc/cmdline`"

echo "## Misc System Info:"
if [ -f /etc/motd ]; then
  echo "motd            :"
  cat /etc/motd
fi

if [ $OS != 'SunOS' ]
then
  echo "## Memory Info:"
  cat /proc/meminfo

  echo "## Disk Info:"
  fdisk -l
fi

echo "## Filesystem Info:"
df -h

echo "## Network Info:"
if [ `uname` == 'SunOS' ]
then
  ifconfig -a
else
  ifconfig
fi

echo "## Blade Info:"
if [ -f ./bladeinfo ]; then
	if ./bladeinfo -c 2>/dev/null; then
		./bladeinfo -a
	else
		echo "Note: no IPMI driver, so we cannot gather blade info"
	fi
else
	echo "Note: cannot find bladeinfo script, so cannot extract blade info"
fi
echo "## End of Nodeinfo ===================================================="
