/* 
 * File IntStatistic.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef INTSTATISTIC_HXX_
#define INTSTATISTIC_HXX_
#include "SAFplusTypesCommon.hxx"

#include <string>
#include "clTransaction.hxx"
#include "clMgtProv.hxx"
#include <vector>
#include "clMgtContainer.hxx"

namespace SAFplusTypes
  {

    class IntStatistic : public SAFplus::MgtContainer {
    public:
        SAFplus::MgtProv<unsigned long int> current;
        SAFplus::MgtProv<std::string> history10sec;
        SAFplus::MgtProv<std::string> history1min;
        SAFplus::MgtProv<std::string> history10min;
        SAFplus::MgtProv<std::string> history1hour;
        SAFplus::MgtProv<std::string> history12hour;
        SAFplus::MgtProv<std::string> history1day;
        SAFplus::MgtProv<std::string> history1week;
        SAFplus::MgtProv<std::string> history1month;

    public:
        IntStatistic();
        std::vector<std::string>* getChildNames();

        /*
         * XPATH: /SAFplusTypes/intStatistic/current
         */
        unsigned long int getCurrent();

        /*
         * XPATH: /SAFplusTypes/intStatistic/current
         */
        void setCurrent(unsigned long int currentValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history10sec
         */
        std::string getHistory10sec();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history10sec
         */
        void setHistory10sec(std::string history10secValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1min
         */
        std::string getHistory1min();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1min
         */
        void setHistory1min(std::string history1minValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history10min
         */
        std::string getHistory10min();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history10min
         */
        void setHistory10min(std::string history10minValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1hour
         */
        std::string getHistory1hour();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1hour
         */
        void setHistory1hour(std::string history1hourValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history12hour
         */
        std::string getHistory12hour();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history12hour
         */
        void setHistory12hour(std::string history12hourValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1day
         */
        std::string getHistory1day();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1day
         */
        void setHistory1day(std::string history1dayValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1week
         */
        std::string getHistory1week();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1week
         */
        void setHistory1week(std::string history1weekValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1month
         */
        std::string getHistory1month();

        /*
         * XPATH: /SAFplusTypes/intStatistic/history1month
         */
        void setHistory1month(std::string history1monthValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);
        ~IntStatistic();

    };
}
/* namespace SAFplusTypes */
#endif /* INTSTATISTIC_HXX_ */
