/* 
 * File IntStatistic.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 
#include "SAFplusTypesCommon.hxx"

#include <string>
#include "clTransaction.hxx"
#include "clMgtProv.hxx"
#include <vector>
#include "clMgtContainer.hxx"
#include "IntStatistic.hxx"


namespace SAFplusTypes
  {

    IntStatistic::IntStatistic(): SAFplus::MgtContainer("intStatistic"), current("current"), history10sec("history10sec"), history1min("history1min"), history10min("history10min"), history1hour("history1hour"), history12hour("history12hour"), history1day("history1day"), history1week("history1week"), history1month("history1month")
    {
        this->addChildObject(&current, "current");
        this->addChildObject(&history10sec, "history10sec");
        this->addChildObject(&history1min, "history1min");
        this->addChildObject(&history10min, "history10min");
        this->addChildObject(&history1hour, "history1hour");
        this->addChildObject(&history12hour, "history12hour");
        this->addChildObject(&history1day, "history1day");
        this->addChildObject(&history1week, "history1week");
        this->addChildObject(&history1month, "history1month");
    };

    std::vector<std::string>* IntStatistic::getChildNames()
    {
        std::string childNames[] = { "current", "history10sec", "history1min", "history10min", "history1hour", "history12hour", "history1day", "history1week", "history1month" };
        return new std::vector<std::string> (childNames, childNames + sizeof(childNames) / sizeof(childNames[0]));
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/current
     */
    unsigned long int IntStatistic::getCurrent()
    {
        return this->current.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/current
     */
    void IntStatistic::setCurrent(unsigned long int currentValue, SAFplus::Transaction &txn)
    {
        this->current.set(currentValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history10sec
     */
    std::string IntStatistic::getHistory10sec()
    {
        return this->history10sec.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history10sec
     */
    void IntStatistic::setHistory10sec(std::string history10secValue, SAFplus::Transaction &txn)
    {
        this->history10sec.set(history10secValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1min
     */
    std::string IntStatistic::getHistory1min()
    {
        return this->history1min.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1min
     */
    void IntStatistic::setHistory1min(std::string history1minValue, SAFplus::Transaction &txn)
    {
        this->history1min.set(history1minValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history10min
     */
    std::string IntStatistic::getHistory10min()
    {
        return this->history10min.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history10min
     */
    void IntStatistic::setHistory10min(std::string history10minValue, SAFplus::Transaction &txn)
    {
        this->history10min.set(history10minValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1hour
     */
    std::string IntStatistic::getHistory1hour()
    {
        return this->history1hour.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1hour
     */
    void IntStatistic::setHistory1hour(std::string history1hourValue, SAFplus::Transaction &txn)
    {
        this->history1hour.set(history1hourValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history12hour
     */
    std::string IntStatistic::getHistory12hour()
    {
        return this->history12hour.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history12hour
     */
    void IntStatistic::setHistory12hour(std::string history12hourValue, SAFplus::Transaction &txn)
    {
        this->history12hour.set(history12hourValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1day
     */
    std::string IntStatistic::getHistory1day()
    {
        return this->history1day.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1day
     */
    void IntStatistic::setHistory1day(std::string history1dayValue, SAFplus::Transaction &txn)
    {
        this->history1day.set(history1dayValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1week
     */
    std::string IntStatistic::getHistory1week()
    {
        return this->history1week.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1week
     */
    void IntStatistic::setHistory1week(std::string history1weekValue, SAFplus::Transaction &txn)
    {
        this->history1week.set(history1weekValue,txn);
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1month
     */
    std::string IntStatistic::getHistory1month()
    {
        return this->history1month.value;
    };

    /*
     * XPATH: /SAFplusTypes/intStatistic/history1month
     */
    void IntStatistic::setHistory1month(std::string history1monthValue, SAFplus::Transaction &txn)
    {
        this->history1month.set(history1monthValue,txn);
    };

    IntStatistic::~IntStatistic()
    {
    };

}
/* namespace SAFplusTypes */
