/* 
 * File FaultStatistic.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef FAULTSTATISTIC_HXX_
#define FAULTSTATISTIC_HXX_

#include <vector>
#include "clMgtContainer.hxx"
#include "clTransaction.hxx"
#include "FaultHistoryEntity.hxx"
#include "clMgtProv.hxx"
#include "clMgtProvList.hxx"

namespace SAFplus
  {

    class FaultStatistic : public SAFplus::MgtContainer
    {
    public:
        SAFplus::MgtProv<FaultHistoryEntity> current;
        SAFplus::MgtProvList<FaultHistoryEntity> history10sec;
        SAFplus::MgtProvList<FaultHistoryEntity> history1min;
        SAFplus::MgtProvList<FaultHistoryEntity> history10min;

    public:
        FaultStatistic();
        std::vector<std::string>* getChildNames();

        /*
         * XPATH: /SAFplusI/FaultStatistic/current
         */
        FaultHistoryEntity getCurrent();

        /*
         * XPATH: /SAFplusI/FaultStatistic/current
         */
        void setCurrent(FaultHistoryEntity currentValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusI/FaultStatistic/history10sec
         */
        std::vector<FaultHistoryEntity> getHistory10sec();

        /*
         * XPATH: /SAFplusI/FaultStatistic/history10sec
         */
        void setHistory10sec(FaultHistoryEntity history10secValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusI/FaultStatistic/history1min
         */
        std::vector<FaultHistoryEntity> getHistory1min();

        /*
         * XPATH: /SAFplusI/FaultStatistic/history1min
         */
        void setHistory1min(FaultHistoryEntity history1minValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);

        /*
         * XPATH: /SAFplusI/FaultStatistic/history10min
         */
        std::vector<FaultHistoryEntity> getHistory10min();

        /*
         * XPATH: /SAFplusI/FaultStatistic/history10min
         */
        void setHistory10min(FaultHistoryEntity history10minValue, SAFplus::Transaction &txn=SAFplus::NO_TXN);
        ~FaultStatistic();

        void printFaultHistory();

    };
}
/* namespace SAFplusI */
#endif /* FAULTSTATISTIC_HXX_ */
