<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aspSUs"
    nsURI="aspSUs.ecore" nsPrefix="aspSUs">
  <eClassifiers xsi:type="ecore:EClass" name="aspSUs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NodeClassType" lowerBound="1"
        eType="#//AmsNodeClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspSu" upperBound="-1"
        eType="#//aspSUType" defaultValueLiteral="" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="aspSUType">
    <eAnnotations source="CWAnnotation">
      <details key="NameField" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=" " unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=" " unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AmsNodeClass">
    <eLiterals name="CL_AMS_NODE_CLASS_A"/>
    <eLiterals name="CL_AMS_NODE_CLASS_B" value="1"/>
    <eLiterals name="CL_AMS_NODE_CLASS_C" value="2"/>
    <eLiterals name="CL_AMS_NODE_CLASS_D" value="3"/>
  </eClassifiers>
</ecore:EPackage>
