<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="clusterLayout"
    nsURI="clusterLayout.ecore" nsPrefix="clusterLayout">
  <eClassifiers xsi:type="ecore:EClass" name="CONFIG">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CHASSISSTYLE" lowerBound="1"
        eType="#//ChassisStyleEnum" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Chassis Type"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChassisStyleEnum">
    <eLiterals name="5slotATCAHorizontal"/>
    <eLiterals name="14slotATCAVertical" value="1"/>
  </eClassifiers>
</ecore:EPackage>
