<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eoConfigurations"
    nsURI="eoConfig.ecore" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="EOList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eoConfig" upperBound="-1"
        eType="#//EOConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOMemConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heapConfig" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Default"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Heap Config"/>
        <details key="isBlankAllowed" value="false"/>
        <details key="editor" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.customeditor.EOMemoryConfigComboBoxCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferConfig" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Default"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Buffer Config"/>
        <details key="isBlankAllowed" value="false"/>
        <details key="editor" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.customeditor.EOMemoryConfigComboBoxCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryConfig" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Default"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Memory Config"/>
        <details key="isBlankAllowed" value="false"/>
        <details key="editor" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.customeditor.EOMemoryConfigComboBoxCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOConfig">
    <eAnnotations source="CWAnnotation">
      <details key="isTreeDumbNode" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Name"/>
        <details key="canModify" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eoMemConfig" lowerBound="1"
        eType="#//EOMemConfig" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="EO Memory Config"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eoIocConfig" lowerBound="1"
        eType="#//EOIOCConfig" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="EO IOC Config"/>
        <details key="isHidden" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOIOCConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iocConfig" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="IOC Config"/>
        <details key="editor" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.customeditor.EOMemoryConfigComboBoxCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
