<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resourceAssociation"
    nsURI="resourceAssociation.ecore" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//associationType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compName" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scalarName" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="-1" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="associationInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="associationType">
    <eLiterals name="instance"/>
    <eLiterals name="sharedInstance" value="1"/>
    <eLiterals name="arrayOfInstance" value="2"/>
    <eLiterals name="arrayOfSharedInstance" value="3"/>
  </eClassifiers>
</ecore:EPackage>
