/* 
 * File Timeticks.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 
#include "ietfYangTypesCommon.hxx"

#include <iostream>
#include "clTransaction.hxx"
#include <cstdint>
#include "Timeticks.hxx"


namespace ietfYangTypes
  {

    Timeticks::Timeticks()
    {
    };

    ::uint32_t Timeticks::getValue()
    {
        return this->value;
    };

    void Timeticks::setValue(::uint32_t value, SAFplus::Transaction &t)
    {
        if(&t == &SAFplus::NO_TXN) this->value = value;
        else
        {
            SAFplus::SimpleTxnOperation<::uint32_t> *opt = new SAFplus::SimpleTxnOperation<::uint32_t>(&this->value,value);
            t.addOperation(opt);
        }
    };

    ietfYangTypes::Timeticks& Timeticks::operator=(const ietfYangTypes::Timeticks &timeticks)
    {
        value = timeticks.value;
        return *this;
    };

    Timeticks::~Timeticks()
    {
    };

    std::ostream& operator<<(std::ostream &os, const ietfYangTypes::Timeticks &timeticks)
    {
        return os << timeticks.value;
    };

    std::istream& operator>>(std::istream &is, ietfYangTypes::Timeticks &timeticks)
    {
        return is >> timeticks.value;
    };

}
/* namespace ietfYangTypes */
