/* 
 * File IANAItuEventType.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#include "IANAITUALARMTCMIBCommon.hxx"
#include <iostream>
#include "MgtEnumType.hxx"
#include "IANAItuEventType.hxx"


namespace IANAITUALARMTCMIB
  {

    /*
     * Provide an implementation of the en2str_map lookup table.
     */
    const IANAItuEventTypeManager::map_t IANAItuEventTypeManager::en2str_map = {
            pair_t(IANAItuEventType::other, "other"),
            pair_t(IANAItuEventType::communicationsAlarm, "communicationsAlarm"),
            pair_t(IANAItuEventType::qualityOfServiceAlarm, "qualityOfServiceAlarm"),
            pair_t(IANAItuEventType::processingErrorAlarm, "processingErrorAlarm"),
            pair_t(IANAItuEventType::equipmentAlarm, "equipmentAlarm"),
            pair_t(IANAItuEventType::environmentalAlarm, "environmentalAlarm"),
            pair_t(IANAItuEventType::integrityViolation, "integrityViolation"),
            pair_t(IANAItuEventType::operationalViolation, "operationalViolation"),
            pair_t(IANAItuEventType::physicalViolation, "physicalViolation"),
            pair_t(IANAItuEventType::securityServiceOrMechanismViolation, "securityServiceOrMechanismViolation"),
            pair_t(IANAItuEventType::timeDomainViolation, "timeDomainViolation")
    }; // uses c++11 initializer lists 

    const char* c_str(const ::IANAITUALARMTCMIB::IANAItuEventType &iANAItuEventType)
    {
        return IANAItuEventTypeManager::c_str(iANAItuEventType);
    };

    std::ostream& operator<<(std::ostream &os, const ::IANAITUALARMTCMIB::IANAItuEventType &iANAItuEventType)
    {
        return os << IANAItuEventTypeManager::toString(iANAItuEventType);
    };

    std::istream& operator>>(std::istream &is, ::IANAITUALARMTCMIB::IANAItuEventType &iANAItuEventType)
    {
        std::string buf;
        is >> buf;
        iANAItuEventType = IANAItuEventTypeManager::toEnum(buf);
        return is;
    };

}
/* namespace ::IANAITUALARMTCMIB */
