REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=safcompliance
DOCTITLE=SA Forum Compliance
DOCURL=Doc:sdk_$(REL)\/safcompliance
PARTNUMBER=000103
INPUT_WIKI_FORMAT=singlepage
OUTPUT_HTML_FORMAT=multipage1

# Makefile for generating html and pdf doc for SA Forum Compliance

include ../tools/Makefile.in
