
/*********************************************************************
* File: 
*********************************************************************/
/*********************************************************************
* Description : This file contains the declartions for server stub
*               routines
*     
* THIS FILE IS AUTO-GENERATED BY OPENCLOVIS IDE. EDIT THIS FILE AT
* YOUR OWN RISK. ANY CHANGE TO THIS FILE WILL BE OVERWRITTEN ON
* RE-GENERATION.
*     
*********************************************************************/

#ifndef _LOGPORTSVR_SERVER_H_
#define _LOGPORTSVR_SERVER_H_
#ifdef __cplusplus
extern "C" {
#endif
#include <clXdrApi.h>
#include <clIdlApi.h>
#include <ipi/clRmdIpi.h>
#include "../clientIDDefinitions.h"
#include "xdrClLogFilterT.h"
#include "xdrClLogStreamAttrIDLT.h"
#include "xdrClLogCompDataT.h"



ClRcT clLogSvrStreamOpen_4_0_0(CL_IN ClNameT*  streamName, CL_IN ClUint32T  streamScope, CL_IN ClNameT*  streamScopeNode, CL_IN ClLogStreamAttrIDLT_4_0_0*  pStreamAttr, CL_IN ClUint8T  streamOpenFlags, CL_IN ClUint32T  compId, CL_IN ClUint32T  portId, CL_OUT ClStringT*  pShmName, CL_OUT ClUint32T*  pShmSize);

ClRcT clLogSvrStreamOpenResponseSend_4_0_0(CL_IN ClIdlHandleT idlHdl,CL_IN ClRcT retCode,CL_OUT  ClStringT  pShmName,CL_OUT  ClUint32T  pShmSize);

ClRcT clLogSvrStreamClose_4_0_0(CL_IN ClNameT*  streamName, CL_IN ClUint32T  streamScope, CL_IN ClNameT*  streamScopeNode, CL_IN ClUint32T  compId);

ClRcT clLogSvrStreamCloseResponseSend_4_0_0(CL_IN ClIdlHandleT idlHdl,CL_IN ClRcT retCode);

ClRcT clLogSvrFilterSet_4_0_0(CL_IN ClNameT*  pStreamName, CL_IN ClUint32T  streamScope, CL_IN ClNameT*  pStreamScopeNode, CL_IN ClLogFilterT_4_0_0*  pFilter);

ClRcT clLogSvrFilterSetResponseSend_4_0_0(CL_IN ClIdlHandleT idlHdl,CL_IN ClRcT retCode);

ClRcT clLogSvrStreamHandleFlagsUpdate_4_0_0(CL_IN ClNameT*  pStreamName, CL_IN ClUint32T  streamScope, CL_IN ClNameT*  pStreamScopeNode, CL_IN ClUint8T  handleFlags, CL_IN ClUint16T  setFlags);

ClRcT clLogSvrStreamHandleFlagsUpdateResponseSend_4_0_0(CL_IN ClIdlHandleT idlHdl,CL_IN ClRcT retCode);

ClRcT clLogHandlerSvrAckSend_4_0_0(CL_IN ClNameT*  pStreamName, CL_IN ClNameT*  pNodeName, CL_IN ClUint32T  streamScope, CL_IN ClUint32T  sequenceNumber, CL_IN ClUint32T  numRecords, CL_IN ClHandleT  flushCookie);

ClRcT clLogHandlerSvrAckSendResponseSend_4_0_0(CL_IN ClIdlHandleT idlHdl,CL_IN ClRcT retCode);


#ifdef __cplusplus
}
#endif
#endif /*_LOGPORTSVR_SERVER_H_*/
