// Generated by the protocol buffer compiler.
#pragma once
#include <string>

#include <google/protobuf/stubs/common.h>
#include <rpcTest.pb.h>

namespace SAFplus {
namespace Rpc {
namespace rpcTest {
class rpcTestImpl : public rpcTest {
 public:
  rpcTestImpl();
  ~rpcTestImpl();

  // implements rpcTestImpl 
  void testGetRpcMethod(::google::protobuf::RpcController* controller,
                       const ::SAFplus::Rpc::rpcTest::TestGetRpcMethodRequest* request,
                       ::SAFplus::Rpc::rpcTest::TestGetRpcMethodResponse* response,
                       ::google::protobuf::Closure* done);
  void testGetRpcMethod2(::google::protobuf::RpcController* controller,
                       const ::SAFplus::Rpc::rpcTest::TestGetRpcMethod2Request* request,
                       ::SAFplus::Rpc::rpcTest::TestGetRpcMethod2Response* response,
                       ::google::protobuf::Closure* done);
  void testGetRpcMethod3(::google::protobuf::RpcController* controller,
                       const ::SAFplus::Rpc::rpcTest::TestGetRpcMethod3Request* request,
                       ::SAFplus::Rpc::rpcTest::TestGetRpcMethod3Response* response,
                       ::google::protobuf::Closure* done);
};

}  // namespace rpcTest
}  // namespace Rpc
}  // namespace SAFplus
