REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=tutorial
DOCTITLE=Sample Application Tutorial
DOCURL=Doc:sdk_$(REL)\/tutorial
PARTNUMBER=000104
INPUT_WIKI_FORMAT=singlepage
OUTPUT_HTML_FORMAT=multipage1

# Makefile for generating html and pdf doc for Modeling Tutorial

include ../tools/Makefile.in
