#!/bin/bash

pkill -9 safplus_amf
pkill -9 safplus_group

rm -f /dev/shm/SAFplus* /dev/shm/ckpt*

ME=`whoami`
IPCS_S=`ipcs -s | egrep "0x[0-9a-f]+ [0-9]+" | grep $ME | cut -f2 -d" "`
for id in $IPCS_S; do
  ipcrm -s $id;
done
