// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcTest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rpcTest.pb.hxx"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SAFplus {
namespace Rpc {
namespace rpcTest {

namespace {

const ::google::protobuf::Descriptor* TestGetRpcMethodRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethodRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* DataResult2_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DataResult2_reflection_ = NULL;
const ::google::protobuf::Descriptor* DataResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DataResult_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestGetRpcMethodResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethodResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestGetRpcMethod2Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethod2Request_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestGetRpcMethod2Response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethod2Response_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestGetRpcMethod3Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethod3Request_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestGetRpcMethod3Response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestGetRpcMethod3Response_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_rpcTest_2eproto() {
  protobuf_AddDesc_rpcTest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "rpcTest.proto");
  GOOGLE_CHECK(file != NULL);
  TestGetRpcMethodRequest_descriptor_ = file->message_type(0);
  static const int TestGetRpcMethodRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodRequest, name_),
  };
  TestGetRpcMethodRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethodRequest_descriptor_,
      TestGetRpcMethodRequest::default_instance_,
      TestGetRpcMethodRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodRequest, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodRequest, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethodRequest));
  DataResult2_descriptor_ = file->message_type(1);
  static const int DataResult2_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult2, option2_),
  };
  DataResult2_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DataResult2_descriptor_,
      DataResult2::default_instance_,
      DataResult2_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult2, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult2, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult2, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DataResult2));
  DataResult_descriptor_ = file->message_type(2);
  static const int DataResult_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, testbinary_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, dataresult2_),
  };
  DataResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DataResult_descriptor_,
      DataResult::default_instance_,
      DataResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DataResult, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DataResult));
  TestGetRpcMethodResponse_descriptor_ = file->message_type(3);
  static const int TestGetRpcMethodResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodResponse, dataresult_),
  };
  TestGetRpcMethodResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethodResponse_descriptor_,
      TestGetRpcMethodResponse::default_instance_,
      TestGetRpcMethodResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodResponse, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethodResponse, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethodResponse));
  TestGetRpcMethod2Request_descriptor_ = file->message_type(4);
  static const int TestGetRpcMethod2Request_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Request, name_),
  };
  TestGetRpcMethod2Request_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethod2Request_descriptor_,
      TestGetRpcMethod2Request::default_instance_,
      TestGetRpcMethod2Request_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Request, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Request, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Request, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethod2Request));
  TestGetRpcMethod2Response_descriptor_ = file->message_type(5);
  static const int TestGetRpcMethod2Response_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Response, dataresult_),
  };
  TestGetRpcMethod2Response_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethod2Response_descriptor_,
      TestGetRpcMethod2Response::default_instance_,
      TestGetRpcMethod2Response_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Response, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Response, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod2Response, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethod2Response));
  TestGetRpcMethod3Request_descriptor_ = file->message_type(6);
  static const int TestGetRpcMethod3Request_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Request, name_),
  };
  TestGetRpcMethod3Request_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethod3Request_descriptor_,
      TestGetRpcMethod3Request::default_instance_,
      TestGetRpcMethod3Request_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Request, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Request, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Request, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethod3Request));
  TestGetRpcMethod3Response_descriptor_ = file->message_type(7);
  static const int TestGetRpcMethod3Response_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Response, dataresult_),
  };
  TestGetRpcMethod3Response_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestGetRpcMethod3Response_descriptor_,
      TestGetRpcMethod3Response::default_instance_,
      TestGetRpcMethod3Response_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Response, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Response, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestGetRpcMethod3Response, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestGetRpcMethod3Response));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_rpcTest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethodRequest_descriptor_, &TestGetRpcMethodRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DataResult2_descriptor_, &DataResult2::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DataResult_descriptor_, &DataResult::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethodResponse_descriptor_, &TestGetRpcMethodResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethod2Request_descriptor_, &TestGetRpcMethod2Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethod2Response_descriptor_, &TestGetRpcMethod2Response::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethod3Request_descriptor_, &TestGetRpcMethod3Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestGetRpcMethod3Response_descriptor_, &TestGetRpcMethod3Response::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_rpcTest_2eproto() {
  delete TestGetRpcMethodRequest::default_instance_;
  delete TestGetRpcMethodRequest_reflection_;
  delete DataResult2::default_instance_;
  delete DataResult2_reflection_;
  delete DataResult::default_instance_;
  delete DataResult_reflection_;
  delete TestGetRpcMethodResponse::default_instance_;
  delete TestGetRpcMethodResponse_reflection_;
  delete TestGetRpcMethod2Request::default_instance_;
  delete TestGetRpcMethod2Request_reflection_;
  delete TestGetRpcMethod2Response::default_instance_;
  delete TestGetRpcMethod2Response_reflection_;
  delete TestGetRpcMethod3Request::default_instance_;
  delete TestGetRpcMethod3Request_reflection_;
  delete TestGetRpcMethod3Response::default_instance_;
  delete TestGetRpcMethod3Response_reflection_;
}

void protobuf_AddDesc_rpcTest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::SAFplus::Rpc::protobuf_AddDesc_SAFplusPBExt_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rrpcTest.proto\022\023SAFplus.Rpc.rpcTest\032\022SA"
    "FplusPBExt.proto\"2\n\027TestGetRpcMethodRequ"
    "est\022\014\n\004name\030\001 \001(\t*\t\010\350\007\020\200\200\200\200\002\")\n\013DataResu"
    "lt2\022\017\n\007option2\030\001 \003(\014*\t\010\350\007\020\200\200\200\200\002\"\200\001\n\nData"
    "Result\022\014\n\004name\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\022\n\n"
    "testbinary\030\003 \003(\014\0225\n\013dataResult2\030\004 \001(\0132 ."
    "SAFplus.Rpc.rpcTest.DataResult2*\t\010\350\007\020\200\200\200"
    "\200\002\"Z\n\030TestGetRpcMethodResponse\0223\n\ndataRe"
    "sult\030\001 \001(\0132\037.SAFplus.Rpc.rpcTest.DataRes"
    "ult*\t\010\350\007\020\200\200\200\200\002\"3\n\030TestGetRpcMethod2Reque"
    "st\022\014\n\004name\030\001 \001(\t*\t\010\350\007\020\200\200\200\200\002\"[\n\031TestGetRp"
    "cMethod2Response\0223\n\ndataResult\030\001 \001(\0132\037.S"
    "AFplus.Rpc.rpcTest.DataResult*\t\010\350\007\020\200\200\200\200\002"
    "\"3\n\030TestGetRpcMethod3Request\022\014\n\004name\030\001 \001"
    "(\t*\t\010\350\007\020\200\200\200\200\002\"[\n\031TestGetRpcMethod3Respon"
    "se\0223\n\ndataResult\030\001 \001(\0132\037.SAFplus.Rpc.rpc"
    "Test.DataResult*\t\010\350\007\020\200\200\200\200\0022\342\002\n\007rpcTest\022o"
    "\n\020testGetRpcMethod\022,.SAFplus.Rpc.rpcTest"
    ".TestGetRpcMethodRequest\032-.SAFplus.Rpc.r"
    "pcTest.TestGetRpcMethodResponse\022r\n\021testG"
    "etRpcMethod2\022-.SAFplus.Rpc.rpcTest.TestG"
    "etRpcMethod2Request\032..SAFplus.Rpc.rpcTes"
    "t.TestGetRpcMethod2Response\022r\n\021testGetRp"
    "cMethod3\022-.SAFplus.Rpc.rpcTest.TestGetRp"
    "cMethod3Request\032..SAFplus.Rpc.rpcTest.Te"
    "stGetRpcMethod3ResponseB\t\200\001\000\210\001\000\220\001\001", 1034);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rpcTest.proto", &protobuf_RegisterTypes);
  TestGetRpcMethodRequest::default_instance_ = new TestGetRpcMethodRequest();
  DataResult2::default_instance_ = new DataResult2();
  DataResult::default_instance_ = new DataResult();
  TestGetRpcMethodResponse::default_instance_ = new TestGetRpcMethodResponse();
  TestGetRpcMethod2Request::default_instance_ = new TestGetRpcMethod2Request();
  TestGetRpcMethod2Response::default_instance_ = new TestGetRpcMethod2Response();
  TestGetRpcMethod3Request::default_instance_ = new TestGetRpcMethod3Request();
  TestGetRpcMethod3Response::default_instance_ = new TestGetRpcMethod3Response();
  TestGetRpcMethodRequest::default_instance_->InitAsDefaultInstance();
  DataResult2::default_instance_->InitAsDefaultInstance();
  DataResult::default_instance_->InitAsDefaultInstance();
  TestGetRpcMethodResponse::default_instance_->InitAsDefaultInstance();
  TestGetRpcMethod2Request::default_instance_->InitAsDefaultInstance();
  TestGetRpcMethod2Response::default_instance_->InitAsDefaultInstance();
  TestGetRpcMethod3Request::default_instance_->InitAsDefaultInstance();
  TestGetRpcMethod3Response::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_rpcTest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_rpcTest_2eproto {
  StaticDescriptorInitializer_rpcTest_2eproto() {
    protobuf_AddDesc_rpcTest_2eproto();
  }
} static_descriptor_initializer_rpcTest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethodRequest::kNameFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethodRequest::TestGetRpcMethodRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethodRequest::InitAsDefaultInstance() {
}

TestGetRpcMethodRequest::TestGetRpcMethodRequest(const TestGetRpcMethodRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethodRequest::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethodRequest::~TestGetRpcMethodRequest() {
  SharedDtor();
}

void TestGetRpcMethodRequest::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void TestGetRpcMethodRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethodRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethodRequest_descriptor_;
}

const TestGetRpcMethodRequest& TestGetRpcMethodRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethodRequest* TestGetRpcMethodRequest::default_instance_ = NULL;

TestGetRpcMethodRequest* TestGetRpcMethodRequest::New() const {
  return new TestGetRpcMethodRequest;
}

void TestGetRpcMethodRequest::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethodRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethodRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethodRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethodRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethodRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethodRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethodRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethodRequest::MergeFrom(const TestGetRpcMethodRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethodRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethodRequest::CopyFrom(const TestGetRpcMethodRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethodRequest::IsInitialized() const {


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethodRequest::Swap(TestGetRpcMethodRequest* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethodRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethodRequest_descriptor_;
  metadata.reflection = TestGetRpcMethodRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DataResult2::kOption2FieldNumber;
#endif  // !_MSC_VER

DataResult2::DataResult2()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DataResult2::InitAsDefaultInstance() {
}

DataResult2::DataResult2(const DataResult2& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DataResult2::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DataResult2::~DataResult2() {
  SharedDtor();
}

void DataResult2::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DataResult2::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DataResult2::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DataResult2_descriptor_;
}

const DataResult2& DataResult2::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

DataResult2* DataResult2::default_instance_ = NULL;

DataResult2* DataResult2::New() const {
  return new DataResult2;
}

void DataResult2::Clear() {
  _extensions_.Clear();
  option2_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DataResult2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes option2 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_option2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_option2()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_option2;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DataResult2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated bytes option2 = 1;
  for (int i = 0; i < this->option2_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->option2(i), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DataResult2::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated bytes option2 = 1;
  for (int i = 0; i < this->option2_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->option2(i), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DataResult2::ByteSize() const {
  int total_size = 0;

  // repeated bytes option2 = 1;
  total_size += 1 * this->option2_size();
  for (int i = 0; i < this->option2_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->option2(i));
  }

  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DataResult2::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DataResult2* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DataResult2*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DataResult2::MergeFrom(const DataResult2& from) {
  GOOGLE_CHECK_NE(&from, this);
  option2_.MergeFrom(from.option2_);
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DataResult2::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataResult2::CopyFrom(const DataResult2& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataResult2::IsInitialized() const {


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void DataResult2::Swap(DataResult2* other) {
  if (other != this) {
    option2_.Swap(&other->option2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata DataResult2::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DataResult2_descriptor_;
  metadata.reflection = DataResult2_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DataResult::kNameFieldNumber;
const int DataResult::kStatusFieldNumber;
const int DataResult::kTestbinaryFieldNumber;
const int DataResult::kDataResult2FieldNumber;
#endif  // !_MSC_VER

DataResult::DataResult()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DataResult::InitAsDefaultInstance() {
  dataresult2_ = const_cast< ::SAFplus::Rpc::rpcTest::DataResult2*>(&::SAFplus::Rpc::rpcTest::DataResult2::default_instance());
}

DataResult::DataResult(const DataResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DataResult::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  status_ = 0;
  dataresult2_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DataResult::~DataResult() {
  SharedDtor();
}

void DataResult::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
    delete dataresult2_;
  }
}

void DataResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DataResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DataResult_descriptor_;
}

const DataResult& DataResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

DataResult* DataResult::default_instance_ = NULL;

DataResult* DataResult::New() const {
  return new DataResult;
}

void DataResult::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    status_ = 0;
    if (has_dataresult2()) {
      if (dataresult2_ != NULL) dataresult2_->::SAFplus::Rpc::rpcTest::DataResult2::Clear();
    }
  }
  testbinary_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DataResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_status;
        break;
      }

      // optional int32 status = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
          set_has_status();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_testbinary;
        break;
      }

      // repeated bytes testbinary = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_testbinary:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_testbinary()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_testbinary;
        if (input->ExpectTag(34)) goto parse_dataResult2;
        break;
      }

      // optional .SAFplus.Rpc.rpcTest.DataResult2 dataResult2 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dataResult2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dataresult2()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DataResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // optional int32 status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->status(), output);
  }

  // repeated bytes testbinary = 3;
  for (int i = 0; i < this->testbinary_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->testbinary(i), output);
  }

  // optional .SAFplus.Rpc.rpcTest.DataResult2 dataResult2 = 4;
  if (has_dataresult2()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->dataresult2(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DataResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->status(), target);
  }

  // repeated bytes testbinary = 3;
  for (int i = 0; i < this->testbinary_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(3, this->testbinary(i), target);
  }

  // optional .SAFplus.Rpc.rpcTest.DataResult2 dataResult2 = 4;
  if (has_dataresult2()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->dataresult2(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DataResult::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->status());
    }

    // optional .SAFplus.Rpc.rpcTest.DataResult2 dataResult2 = 4;
    if (has_dataresult2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dataresult2());
    }

  }
  // repeated bytes testbinary = 3;
  total_size += 1 * this->testbinary_size();
  for (int i = 0; i < this->testbinary_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->testbinary(i));
  }

  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DataResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DataResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DataResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DataResult::MergeFrom(const DataResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  testbinary_.MergeFrom(from.testbinary_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_dataresult2()) {
      mutable_dataresult2()->::SAFplus::Rpc::rpcTest::DataResult2::MergeFrom(from.dataresult2());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DataResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataResult::CopyFrom(const DataResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataResult::IsInitialized() const {

  if (has_dataresult2()) {
    if (!this->dataresult2().IsInitialized()) return false;
  }

  if (!_extensions_.IsInitialized()) return false;  return true;
}

void DataResult::Swap(DataResult* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(status_, other->status_);
    testbinary_.Swap(&other->testbinary_);
    std::swap(dataresult2_, other->dataresult2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata DataResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DataResult_descriptor_;
  metadata.reflection = DataResult_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethodResponse::kDataResultFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethodResponse::TestGetRpcMethodResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethodResponse::InitAsDefaultInstance() {
  dataresult_ = const_cast< ::SAFplus::Rpc::rpcTest::DataResult*>(&::SAFplus::Rpc::rpcTest::DataResult::default_instance());
}

TestGetRpcMethodResponse::TestGetRpcMethodResponse(const TestGetRpcMethodResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethodResponse::SharedCtor() {
  _cached_size_ = 0;
  dataresult_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethodResponse::~TestGetRpcMethodResponse() {
  SharedDtor();
}

void TestGetRpcMethodResponse::SharedDtor() {
  if (this != default_instance_) {
    delete dataresult_;
  }
}

void TestGetRpcMethodResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethodResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethodResponse_descriptor_;
}

const TestGetRpcMethodResponse& TestGetRpcMethodResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethodResponse* TestGetRpcMethodResponse::default_instance_ = NULL;

TestGetRpcMethodResponse* TestGetRpcMethodResponse::New() const {
  return new TestGetRpcMethodResponse;
}

void TestGetRpcMethodResponse::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_dataresult()) {
      if (dataresult_ != NULL) dataresult_->::SAFplus::Rpc::rpcTest::DataResult::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethodResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dataresult()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethodResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->dataresult(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethodResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->dataresult(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethodResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
    if (has_dataresult()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dataresult());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethodResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethodResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethodResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethodResponse::MergeFrom(const TestGetRpcMethodResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dataresult()) {
      mutable_dataresult()->::SAFplus::Rpc::rpcTest::DataResult::MergeFrom(from.dataresult());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethodResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethodResponse::CopyFrom(const TestGetRpcMethodResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethodResponse::IsInitialized() const {

  if (has_dataresult()) {
    if (!this->dataresult().IsInitialized()) return false;
  }

  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethodResponse::Swap(TestGetRpcMethodResponse* other) {
  if (other != this) {
    std::swap(dataresult_, other->dataresult_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethodResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethodResponse_descriptor_;
  metadata.reflection = TestGetRpcMethodResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethod2Request::kNameFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethod2Request::TestGetRpcMethod2Request()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethod2Request::InitAsDefaultInstance() {
}

TestGetRpcMethod2Request::TestGetRpcMethod2Request(const TestGetRpcMethod2Request& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethod2Request::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethod2Request::~TestGetRpcMethod2Request() {
  SharedDtor();
}

void TestGetRpcMethod2Request::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void TestGetRpcMethod2Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethod2Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethod2Request_descriptor_;
}

const TestGetRpcMethod2Request& TestGetRpcMethod2Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethod2Request* TestGetRpcMethod2Request::default_instance_ = NULL;

TestGetRpcMethod2Request* TestGetRpcMethod2Request::New() const {
  return new TestGetRpcMethod2Request;
}

void TestGetRpcMethod2Request::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethod2Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethod2Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethod2Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethod2Request::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethod2Request::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethod2Request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethod2Request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethod2Request::MergeFrom(const TestGetRpcMethod2Request& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethod2Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethod2Request::CopyFrom(const TestGetRpcMethod2Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethod2Request::IsInitialized() const {


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethod2Request::Swap(TestGetRpcMethod2Request* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethod2Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethod2Request_descriptor_;
  metadata.reflection = TestGetRpcMethod2Request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethod2Response::kDataResultFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethod2Response::TestGetRpcMethod2Response()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethod2Response::InitAsDefaultInstance() {
  dataresult_ = const_cast< ::SAFplus::Rpc::rpcTest::DataResult*>(&::SAFplus::Rpc::rpcTest::DataResult::default_instance());
}

TestGetRpcMethod2Response::TestGetRpcMethod2Response(const TestGetRpcMethod2Response& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethod2Response::SharedCtor() {
  _cached_size_ = 0;
  dataresult_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethod2Response::~TestGetRpcMethod2Response() {
  SharedDtor();
}

void TestGetRpcMethod2Response::SharedDtor() {
  if (this != default_instance_) {
    delete dataresult_;
  }
}

void TestGetRpcMethod2Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethod2Response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethod2Response_descriptor_;
}

const TestGetRpcMethod2Response& TestGetRpcMethod2Response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethod2Response* TestGetRpcMethod2Response::default_instance_ = NULL;

TestGetRpcMethod2Response* TestGetRpcMethod2Response::New() const {
  return new TestGetRpcMethod2Response;
}

void TestGetRpcMethod2Response::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_dataresult()) {
      if (dataresult_ != NULL) dataresult_->::SAFplus::Rpc::rpcTest::DataResult::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethod2Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dataresult()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethod2Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->dataresult(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethod2Response::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->dataresult(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethod2Response::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
    if (has_dataresult()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dataresult());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethod2Response::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethod2Response* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethod2Response*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethod2Response::MergeFrom(const TestGetRpcMethod2Response& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dataresult()) {
      mutable_dataresult()->::SAFplus::Rpc::rpcTest::DataResult::MergeFrom(from.dataresult());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethod2Response::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethod2Response::CopyFrom(const TestGetRpcMethod2Response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethod2Response::IsInitialized() const {

  if (has_dataresult()) {
    if (!this->dataresult().IsInitialized()) return false;
  }

  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethod2Response::Swap(TestGetRpcMethod2Response* other) {
  if (other != this) {
    std::swap(dataresult_, other->dataresult_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethod2Response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethod2Response_descriptor_;
  metadata.reflection = TestGetRpcMethod2Response_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethod3Request::kNameFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethod3Request::TestGetRpcMethod3Request()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethod3Request::InitAsDefaultInstance() {
}

TestGetRpcMethod3Request::TestGetRpcMethod3Request(const TestGetRpcMethod3Request& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethod3Request::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethod3Request::~TestGetRpcMethod3Request() {
  SharedDtor();
}

void TestGetRpcMethod3Request::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void TestGetRpcMethod3Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethod3Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethod3Request_descriptor_;
}

const TestGetRpcMethod3Request& TestGetRpcMethod3Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethod3Request* TestGetRpcMethod3Request::default_instance_ = NULL;

TestGetRpcMethod3Request* TestGetRpcMethod3Request::New() const {
  return new TestGetRpcMethod3Request;
}

void TestGetRpcMethod3Request::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethod3Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethod3Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethod3Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethod3Request::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethod3Request::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethod3Request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethod3Request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethod3Request::MergeFrom(const TestGetRpcMethod3Request& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethod3Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethod3Request::CopyFrom(const TestGetRpcMethod3Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethod3Request::IsInitialized() const {


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethod3Request::Swap(TestGetRpcMethod3Request* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethod3Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethod3Request_descriptor_;
  metadata.reflection = TestGetRpcMethod3Request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestGetRpcMethod3Response::kDataResultFieldNumber;
#endif  // !_MSC_VER

TestGetRpcMethod3Response::TestGetRpcMethod3Response()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestGetRpcMethod3Response::InitAsDefaultInstance() {
  dataresult_ = const_cast< ::SAFplus::Rpc::rpcTest::DataResult*>(&::SAFplus::Rpc::rpcTest::DataResult::default_instance());
}

TestGetRpcMethod3Response::TestGetRpcMethod3Response(const TestGetRpcMethod3Response& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestGetRpcMethod3Response::SharedCtor() {
  _cached_size_ = 0;
  dataresult_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestGetRpcMethod3Response::~TestGetRpcMethod3Response() {
  SharedDtor();
}

void TestGetRpcMethod3Response::SharedDtor() {
  if (this != default_instance_) {
    delete dataresult_;
  }
}

void TestGetRpcMethod3Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestGetRpcMethod3Response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestGetRpcMethod3Response_descriptor_;
}

const TestGetRpcMethod3Response& TestGetRpcMethod3Response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcTest_2eproto();
  return *default_instance_;
}

TestGetRpcMethod3Response* TestGetRpcMethod3Response::default_instance_ = NULL;

TestGetRpcMethod3Response* TestGetRpcMethod3Response::New() const {
  return new TestGetRpcMethod3Response;
}

void TestGetRpcMethod3Response::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_dataresult()) {
      if (dataresult_ != NULL) dataresult_->::SAFplus::Rpc::rpcTest::DataResult::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestGetRpcMethod3Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dataresult()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestGetRpcMethod3Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->dataresult(), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(
      1000, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestGetRpcMethod3Response::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
  if (has_dataresult()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->dataresult(), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestGetRpcMethod3Response::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .SAFplus.Rpc.rpcTest.DataResult dataResult = 1;
    if (has_dataresult()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dataresult());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestGetRpcMethod3Response::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestGetRpcMethod3Response* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestGetRpcMethod3Response*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestGetRpcMethod3Response::MergeFrom(const TestGetRpcMethod3Response& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dataresult()) {
      mutable_dataresult()->::SAFplus::Rpc::rpcTest::DataResult::MergeFrom(from.dataresult());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestGetRpcMethod3Response::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGetRpcMethod3Response::CopyFrom(const TestGetRpcMethod3Response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGetRpcMethod3Response::IsInitialized() const {

  if (has_dataresult()) {
    if (!this->dataresult().IsInitialized()) return false;
  }

  if (!_extensions_.IsInitialized()) return false;  return true;
}

void TestGetRpcMethod3Response::Swap(TestGetRpcMethod3Response* other) {
  if (other != this) {
    std::swap(dataresult_, other->dataresult_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata TestGetRpcMethod3Response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestGetRpcMethod3Response_descriptor_;
  metadata.reflection = TestGetRpcMethod3Response_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpcTest
}  // namespace Rpc
}  // namespace SAFplus

// @@protoc_insertion_point(global_scope)
