/*
 * Copyright (C) 2002-2012 OpenClovis Solutions Inc.  All Rights Reserved.
 *
 * This file is available  under  a  commercial  license  from  the
 * copyright  holder or the GNU General Public License Version 2.0.
 * 
 * The source code for  this program is not published  or otherwise 
 * divested of  its trade secrets, irrespective  of  what  has been 
 * deposited with the U.S. Copyright office.
 * 
 * This program is distributed in the  hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * For more  information, see  the file  COPYING provided with this
 * material.
 */


/*********************************************************************
* ModuleName  : idl
*********************************************************************/
/*********************************************************************
* Description : This file contains the declarations for marshall 
*               and unmarshall funtions of ClMsgSyncActionT_4_0_0 
*     
* THIS FILE IS AUTO-GENERATED BY OPENCLOVIS IDE. EDIT THIS FILE AT
* YOUR OWN RISK. ANY CHANGE TO THIS FILE WILL BE OVERWRITTEN ON
* RE-GENERATION.
*     
*********************************************************************/

#ifndef _XDR_CL_MSG_SYNC_ACTION_T_H_
#define _XDR_CL_MSG_SYNC_ACTION_T_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "clXdrApi.h"
#include "clMsgCommon.h"
#include "clMsgCkptData.h"
#include "clIocApi.h"
#include "clCommon.h"
#include "saMsg.h"
#include "saAis.h"



#define      clXdrMarshallClMsgSyncActionT_4_0_0               clXdrMarshallClInt32T

#define      clXdrUnmarshallClMsgSyncActionT_4_0_0             clXdrUnmarshallClInt32T

#define      clXdrMarshallArrayClMsgSyncActionT_4_0_0          clXdrMarshallArrayClInt32T

#define      clXdrUnmarshallArrayClMsgSyncActionT_4_0_0        clXdrUnmarshallArrayClInt32T

#define      clXdrMarshallPointerClMsgSyncActionT_4_0_0        clXdrMarshallPointerClInt32T

#define      clXdrUnmarshallPointerClMsgSyncActionT_4_0_0      clXdrUnmarshallPointerClInt32T

#define      clXdrMarshallPtrClMsgSyncActionT_4_0_0            clXdrMarshallPtrClInt32T

#define      clXdrUnmarshallPtrClMsgSyncActionT_4_0_0          clXdrUnmarshallPtrClInt32T



typedef ClMsgSyncActionT ClMsgSyncActionT_4_0_0;



#ifdef __cplusplus
}
#endif

#endif /*_XDR_CL_MSG_SYNC_ACTION_T_H_*/
