/*
 * Copyright (C) 2002-2012 OpenClovis Solutions Inc.  All Rights Reserved.
 *
 * This file is available  under  a  commercial  license  from  the
 * copyright  holder or the GNU General Public License Version 2.0.
 * 
 * The source code for  this program is not published  or otherwise 
 * divested of  its trade secrets, irrespective  of  what  has been 
 * deposited with the U.S. Copyright office.
 * 
 * This program is distributed in the  hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * For more  information, see  the file  COPYING provided with this
 * material.
 */


/*********************************************************************
* ModuleName  : idl
*********************************************************************/
/*********************************************************************
* Description : This file contains the declarations for marshall 
*               and unmarshall funtions of ClMsgMessageIovecT 
*     
* THIS FILE IS AUTO-GENERATED BY OPENCLOVIS IDE. EDIT THIS FILE AT
* YOUR OWN RISK. ANY CHANGE TO THIS FILE WILL BE OVERWRITTEN ON
* RE-GENERATION.
*     
*********************************************************************/

#ifndef _XDR_CL_MSG_MESSAGE_IOVEC_T_H_
#define _XDR_CL_MSG_MESSAGE_IOVEC_T_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "clXdrApi.h"

#include "clMsgCommon.h"
#include "clMsgCkptData.h"
#include "clIocApi.h"
#include "clCommon.h"
#include "saMsg.h"
#include "saAis.h"
#include "xdrIovec_t.h"

struct _ClMsgMessageIovecT_4_0_0;


ClRcT  clXdrMarshallClMsgMessageIovecT_4_0_0(void *,ClBufferHandleT , ClUint32T);

ClRcT  clXdrUnmarshallClMsgMessageIovecT_4_0_0(ClBufferHandleT, void *);

#define clXdrMarshallArrayClMsgMessageIovecT_4_0_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallArray((pointer), sizeof(ClMsgMessageIovecT_4_0_0), (multiplicity), clXdrMarshallClMsgMessageIovecT_4_0_0, (msg), (isDelete))

#define clXdrUnmarshallArrayClMsgMessageIovecT_4_0_0(msg,pointer, multiplicity) \
clXdrUnmarshallArray((msg),(pointer), sizeof(ClMsgMessageIovecT_4_0_0), (multiplicity), clXdrUnmarshallClMsgMessageIovecT_4_0_0)

#define clXdrMarshallPointerClMsgMessageIovecT_4_0_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallPointer((pointer), sizeof(ClMsgMessageIovecT_4_0_0), (multiplicity), clXdrMarshallClMsgMessageIovecT_4_0_0, (msg), (isDelete))

#define clXdrUnmarshallPointerClMsgMessageIovecT_4_0_0(msg,pointer) \
clXdrUnmarshallPointer((msg),(pointer), sizeof(ClMsgMessageIovecT_4_0_0), clXdrUnmarshallClMsgMessageIovecT_4_0_0)

#define clXdrMarshallPtrClMsgMessageIovecT_4_0_0(pointer, multiplicity, msg, isDelete) \
clXdrMarshallPtr((pointer), sizeof(ClMsgMessageIovecT_4_0_0), (multiplicity), clXdrMarshallClMsgMessageIovecT_4_0_0, (msg), (isDelete))

#define clXdrUnmarshallPtrClMsgMessageIovecT_4_0_0(msg,pointer,multiplicity) \
clXdrUnmarshallPtr((msg),(pointer), sizeof(ClMsgMessageIovecT_4_0_0),multiplicity, clXdrUnmarshallClMsgMessageIovecT_4_0_0)


typedef ClMsgMessageIovecT ClMsgMessageIovecT_4_0_0;



#ifdef __cplusplus
}
#endif

#endif /*_XDR_CL_MSG_MESSAGE_IOVEC_T_H_*/
