#!/bin/bash
export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
export PYTHONPATH=`pwd`/lib:`pwd`/bin:`pwd`/test:$PYTHONPATH

sysctl -w net.core.wmem_max=10485760
sysctl -w net.core.rmem_max=10485760
sysctl -w net.core.rmem_default=10485760
sysctl -w net.core.wmem_default=10485760

# excessive logging can cause expect's input buffer to fill up, hanging the app on stdout
export CL_LOG_SEVERITY=ERROR
export CL_LOG_CODE_LOCATION_ENABLE=1

# To use UDP broadcasts on the loopback interface I need to enable a broadcast address
export SAFPLUS_BACKPLANE_INTERFACE=eth0

