/* 
 * File Failures.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef FAILURES_HXX_
#define FAILURES_HXX_
#include "SAFplusTypesCommon.hxx"

#include <vector>
#include "MgtFactory.hxx"
#include "IntStatistic.hxx"

namespace SAFplusTypes
  {

    class Failures : public IntStatistic {

        /* Apply MGT object factory */
        MGT_REGISTER(Failures);

    public:
        Failures();
        void toString(std::stringstream &xmlString);
        std::vector<std::string>* getChildNames();
        ~Failures();

    };
}
/* namespace SAFplusTypes */
#endif /* FAILURES_HXX_ */
