REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=logtoolguide
DOCTITLE=Log Tool User Guide
DOCURL=Doc:sdk_$(REL)\/logtoolguide
PARTNUMBER=000108
INPUT_WIKI_FORMAT=singlepage
OUTPUT_HTML_FORMAT=multipage2

# Makefile for generating html and pdf doc for Log Tool Guide

include ../tools/Makefile.in

