/* 
 * File Capacity.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#ifndef CAPACITY_HXX_
#define CAPACITY_HXX_

#include "clMgtObject.hxx"
#include "clMgtProv.hxx"
#include <vector>
#include "MgtFactory.hxx"
#include <string>

namespace SAFplusAmf {

    class Capacity : public ClMgtObject {

        /* Apply MGT object factory */
        REGISTER(Capacity);

    public:
        ClMgtProv<std::string> resource;
        ClMgtProv<long int> value;

    public:
        Capacity();
        Capacity(std::string resourceValue);
        std::vector<std::string> getKeys();
        std::vector<std::string> *getChildNames();

        /*
         * XPATH: /SAFplusAmf/Node/capacity/resource
         */
        std::string getResource();

        /*
         * XPATH: /SAFplusAmf/Node/capacity/resource
         */
        void setResource(std::string resourceValue);

        /*
         * XPATH: /SAFplusAmf/Node/capacity/value
         */
        long int getValue();

        /*
         * XPATH: /SAFplusAmf/Node/capacity/value
         */
        void setValue(long int valueValue);
        ~Capacity();

    };
}
/* namespace SAFplusAmf */
#endif /* CAPACITY_HXX_ */
