/* 
 * File HighAvailabilityReadinessState.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef HIGHAVAILABILITYREADINESSSTATE_HXX_
#define HIGHAVAILABILITYREADINESSSTATE_HXX_
#include "SAFplusAmfCommon.hxx"

#include "MgtEnumType.hxx"
#include <iostream>

namespace SAFplusAmf
  {

    enum class HighAvailabilityReadinessState
  {
        readyForAssignment, readyForActiveDegrated, notReadyForActive, notReadyForAssignment
      };
    std::ostream& operator<<(std::ostream& os, const HighAvailabilityReadinessState& e);
    std::istream& operator>>(std::istream& is, HighAvailabilityReadinessState& e);

    /*
     * This is the class that will handle the conversion for us.
     */
    class HighAvailabilityReadinessStateManager : public SAFplus::MgtEnumType<HighAvailabilityReadinessStateManager, HighAvailabilityReadinessState> {
        HighAvailabilityReadinessStateManager();  // private to prevent instantiation
    public:
        static const vec_t en2str_vec;  // This is the lookup table.
    };
}
/* namespace SAFplusAmf */
#endif /* HIGHAVAILABILITYREADINESSSTATE_HXX_ */
