/* 
 * File NumActiveServiceInstances.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef NUMACTIVESERVICEINSTANCES_HXX_
#define NUMACTIVESERVICEINSTANCES_HXX_
#include "SAFplusAmfCommon.hxx"

#include <vector>
#include "MgtFactory.hxx"
#include "clMgtObject.hxx"

namespace SAFplusAmf
  {

    class NumActiveServiceInstances : public SAFplus::ClMgtObject {

        /* Apply MGT object factory */
        MGT_REGISTER(NumActiveServiceInstances);

    public:

    public:
        NumActiveServiceInstances();
        std::vector<std::string>* getChildNames();
        ~NumActiveServiceInstances();

    };
}
/* namespace SAFplusAmf */
#endif /* NUMACTIVESERVICEINSTANCES_HXX_ */
