/* 
 * File PresenceState.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#include "MgtFactory.hxx"
#include <iostream>
#include "PresenceState.hxx"

using namespace std;

namespace SAFplusAmf {

    /* Apply MGT object factory */
    REGISTERIMPL(PresenceState, /SAFplusAmf/PresenceState)

    PresenceState::PresenceState() {
    };

    int PresenceState::getValue() {
        return this->Value;
    };

    void PresenceState::setValue(int value) {
        this->Value = value;
    };

    PresenceState& PresenceState::operator=(PresenceState& PresenceState) {
        Value = PresenceState.Value;
        return *this;
    };

    PresenceState::~PresenceState() {
    };

    ostream& operator<<(ostream& os, const PresenceState& PresenceState) {
        return os << PresenceState.Value;
    };

    istream& operator>>(istream& in, PresenceState& PresenceState) {
        return in >> PresenceState.Value;
    };

}
/* namespace SAFplusAmf */
