/* 
 * File ReadinessState.cxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#include <iostream>
#include "ReadinessState.hxx"


namespace SAFplusAmf {

     ReadinessState::ReadinessState() {
    };

    int ReadinessState::getValue() {
        return this->Value;
    };

    void ReadinessState::setValue(int value) {
        this->Value = value;
    };

    SAFplusAmf::ReadinessState& ReadinessState::operator=(SAFplusAmf::ReadinessState& ReadinessState) {
        Value = ReadinessState.Value;
        return *this;
    };

     ReadinessState::~ReadinessState() {
    };

    std::ostream& operator<<(std::ostream& os, const SAFplusAmf::ReadinessState& ReadinessState) {
        return os << ReadinessState.Value;
    };

    std::istream& operator>>(std::istream& in, SAFplusAmf::ReadinessState& ReadinessState) {
        return in >> ReadinessState.Value;
    };

}
/* namespace SAFplusAmf */
