/* 
 * File StandbyServiceInstances.hxx
 * This file has been auto-generated by Y2CPP, the
 * plug-in of pyang.
 */ 

#pragma once
#ifndef STANDBYSERVICEINSTANCES_HXX_
#define STANDBYSERVICEINSTANCES_HXX_
#include "SAFplusAmfCommon.hxx"

#include <vector>
#include "MgtFactory.hxx"
#include "clMgtObject.hxx"

namespace SAFplusAmf
  {

    class StandbyServiceInstances : public ClMgtObject {

        /* Apply MGT object factory */
        REGISTER(StandbyServiceInstances);

    public:

    public:
        StandbyServiceInstances();
        std::vector<std::string>* getChildNames();
        ~StandbyServiceInstances();

    };
}
/* namespace SAFplusAmf */
#endif /* STANDBYSERVICEINSTANCES_HXX_ */
