#ifndef _CL_SNMP_SAFAMF_COLUMNS_H
#define _CL_SNMP_SAFAMF_COLUMNS_H

#ifdef __cplusplus
extern "C" {
#endif

/* column number definitions for table saAmfApplicationTable */
#define COLUMN_SAAMFAPPLICATIONNAMEID        1
#define COLUMN_SAAMFAPPLICATIONNAME        2
#define COLUMN_SAAMFAPPLICATIONADMINSTATE        3
#define COLUMN_SAAMFAPPLICATIONCURRNUMSG        4
#define COLUMN_SAAMFAPPLICATIONADMINSTATETRIGGER        5
#define COLUMN_SAAMFAPPLICATIONRESTARTSTATE        6
#define COLUMN_SAAMFAPPLICATIONROWSTATUS        7

/* column number definitions for table saAmfNodeTable */
#define COLUMN_SAAMFNODENAMEID        1
#define COLUMN_SAAMFNODENAME        2
#define COLUMN_SAAMFNODECLMNODE        3
#define COLUMN_SAAMFNODESUFAILOVERPROB        4
#define COLUMN_SAAMFNODESUFAILOVERMAX        5
#define COLUMN_SAAMFNODEADMINSTATE        6
#define COLUMN_SAAMFNODEOPERATIONALSTATE        7
#define COLUMN_SAAMFNODEAUTOREPAIROPTION        8
#define COLUMN_SAAMFNODEREBOOTONTERMINATIONFAIL        9
#define COLUMN_SAAMFNODEREBOOTONINSTANTIATIONFAIL        10
#define COLUMN_SAAMFNODEADMINSTATETRIGGER        11
#define COLUMN_SAAMFNODERESTARTSTATE        12
#define COLUMN_SAAMFNODEREPAIR        13
#define COLUMN_SAAMFNODEROWSTATUS        14

/* column number definitions for table saAmfSGTable */
#define COLUMN_SAAMFSGNAMEID        1
#define COLUMN_SAAMFSGNAME        2
#define COLUMN_SAAMFSGREDMODEL        3
#define COLUMN_SAAMFSGNUMPREFACTIVESUS        4
#define COLUMN_SAAMFSGNUMPREFSTANDBYSUS        5
#define COLUMN_SAAMFSGNUMPREFINSERVICESUS        6
#define COLUMN_SAAMFSGNUMPREFASSIGNEDSUS        7
#define COLUMN_SAAMFSGMAXACTIVESISPERSU        8
#define COLUMN_SAAMFSGMAXSTANDBYSISPERSU        9
#define COLUMN_SAAMFSGADMINSTATE        10
#define COLUMN_SAAMFSGCOMPRESTARTPROB        11
#define COLUMN_SAAMFSGCOMPRESTARTMAX        12
#define COLUMN_SAAMFSGSURESTARTPROB        13
#define COLUMN_SAAMFSGSURESTARTMAX        14
#define COLUMN_SAAMFSGAUTOREPAIROPTION        15
#define COLUMN_SAAMFSGNUMCURRASSIGNEDSU        16
#define COLUMN_SAAMFSGNUMCURRNONINSTANTIATEDSPARESU        17
#define COLUMN_SAAMFSGNUMCURRINSTANTIATEDSPARESU        18
#define COLUMN_SAAMFSGAUTOADJUSTOPTION        19
#define COLUMN_SAAMFSGAUTOADJUSTPROB        20
#define COLUMN_SAAMFSGADJUSTSTATE        21
#define COLUMN_SAAMFSGADMINSTATETRIGGER        22
#define COLUMN_SAAMFSGROWSTATUS        23

/* column number definitions for table saAmfSUTable */
#define COLUMN_SAAMFSUNAMEID        1
#define COLUMN_SAAMFSUNAME        2
#define COLUMN_SAAMFSURANK        3
#define COLUMN_SAAMFSUNUMCOMPONENTS        4
#define COLUMN_SAAMFSUNUMCURRACTIVESIS        5
#define COLUMN_SAAMFSUNUMCURRSTANDBYSIS        6
#define COLUMN_SAAMFSUADMINSTATE        7
#define COLUMN_SAAMFSUFAILOVER        8
#define COLUMN_SAAMFSUREADINESSSTATE        9
#define COLUMN_SAAMFSUOPERSTATE        10
#define COLUMN_SAAMFSUPRESENCESTATE        11
#define COLUMN_SAAMFSUPREINSTANTIABLE        12
#define COLUMN_SAAMFSUISEXTERNAL        13
#define COLUMN_SAAMFSUHOSTEDBYNODE        14
#define COLUMN_SAAMFSUADMINSTATETRIGGER        15
#define COLUMN_SAAMFSURESTARTSTATE        16
#define COLUMN_SAAMFSUEAMTRIGGER        17
#define COLUMN_SAAMFSUREPAIR        18
#define COLUMN_SAAMFSUROWSTATUS        19

/* column number definitions for table saAmfSITable */
#define COLUMN_SAAMFSINAMEID        1
#define COLUMN_SAAMFSINAME        2
#define COLUMN_SAAMFSIRANK        3
#define COLUMN_SAAMFSINUMCSIS        4
#define COLUMN_SAAMFSIPREFNUMASSIGNMENTS        5
#define COLUMN_SAAMFSIADMINSTATE        6
#define COLUMN_SAAMFSIASSIGNMENTSTATE        7
#define COLUMN_SAAMFSINUMCURRACTIVEASSIGNMENTS        8
#define COLUMN_SAAMFSINUMCURRSTANDBYASSIGNMENTS        9
#define COLUMN_SAAMFSIPROTECTEDBYSG        10
#define COLUMN_SAAMFSIADMINSTATETRIGGER        11
#define COLUMN_SAAMFSISWAPSTATE        12
#define COLUMN_SAAMFSIROWSTATUS        13

/* column number definitions for table saAmfSUsperSIRankTable */
#define COLUMN_SAAMFSUSPERSINAMEID        1
#define COLUMN_SAAMFSUSPERSIRANK        2
#define COLUMN_SAAMFSUSPERSINAME        3
#define COLUMN_SAAMFSUSPERSISUNAME        4
#define COLUMN_SAAMFSUSPERSIROWSTATUS        5

/* column number definitions for table saAmfSGSIRankTable */
#define COLUMN_SAAMFSGSIRANKSGNAMEID        1
#define COLUMN_SAAMFSGSIRANK        2
#define COLUMN_SAAMFSGSIRANKSGNAME        3
#define COLUMN_SAAMFSGSIRANKSINAME        4

/* column number definitions for table saAmfSGSURankTable */
#define COLUMN_SAAMFSGSURANKSGNAMEID        1
#define COLUMN_SAAMFSGSURANK        2
#define COLUMN_SAAMFSGSURANKSGNAME        3
#define COLUMN_SAAMFSGSURANKSUNAME        4

/* column number definitions for table saAmfSISIDepTable */
#define COLUMN_SAAMFSISIDEPSINAMEID        1
#define COLUMN_SAAMFSISIDEPDEPNDSINAMEID        2
#define COLUMN_SAAMFSISIDEPSINAME        3
#define COLUMN_SAAMFSISIDEPDEPNDSINAME        4
#define COLUMN_SAAMFSISIDEPTOLTIME        5
#define COLUMN_SAAMFSISIDEPROWSTATUS        6

/* column number definitions for table saAmfCompTable */
#define COLUMN_SAAMFCOMPNAMEID        1
#define COLUMN_SAAMFCOMPNAME        2
#define COLUMN_SAAMFCOMPCAPABILITY        3
#define COLUMN_SAAMFCOMPCATEGORY        4
#define COLUMN_SAAMFCOMPINSTANTIATECMD        5
#define COLUMN_SAAMFCOMPTERMINATECMD        6
#define COLUMN_SAAMFCOMPCLEANUPCMD        7
#define COLUMN_SAAMFCOMPAMSTARTCMD        8
#define COLUMN_SAAMFCOMPAMSTOPCMD        9
#define COLUMN_SAAMFCOMPINSTANTIATIONLEVEL        10
#define COLUMN_SAAMFCOMPDEFAULTCLCCLITIMEOUT        11
#define COLUMN_SAAMFCOMPDEFAULTCALLBACKTIMEOUT        12
#define COLUMN_SAAMFCOMPINSTANTIATETIMEOUT        13
#define COLUMN_SAAMFCOMPDELAYBETWEENINSTANTIATEATTEMPTS        14
#define COLUMN_SAAMFCOMPTERMINATETIMEOUT        15
#define COLUMN_SAAMFCOMPCLEANUPTIMEOUT        16
#define COLUMN_SAAMFCOMPAMSTARTTIMEOUT        17
#define COLUMN_SAAMFCOMPAMSTOPTIMEOUT        18
#define COLUMN_SAAMFCOMPTERMINATECALLBACKTIMEOUT        19
#define COLUMN_SAAMFCOMPCSISETCALLBACKTIMEOUT        20
#define COLUMN_SAAMFCOMPQUIESCINGCOMPLETETIMEOUT        21
#define COLUMN_SAAMFCOMPCSIRMVCALLBACKTIMEOUT        22
#define COLUMN_SAAMFCOMPRECOVERYONERROR        23
#define COLUMN_SAAMFCOMPNUMMAXINSTANTIATEWITHOUTDELAY        24
#define COLUMN_SAAMFCOMPNUMMAXINSTANTIATEWITHDELAY        25
#define COLUMN_SAAMFCOMPNUMMAXAMSTARTSTOPATTEMPTS        26
#define COLUMN_SAAMFCOMPDISABLERESTART        27
#define COLUMN_SAAMFCOMPNUMMAXACTIVECSI        28
#define COLUMN_SAAMFCOMPNUMMAXSTANDBYCSI        29
#define COLUMN_SAAMFCOMPNUMCURRACTIVECSI        30
#define COLUMN_SAAMFCOMPNUMCURRSTANDBYCSI        31
#define COLUMN_SAAMFCOMPRESTARTCOUNT        32
#define COLUMN_SAAMFCOMPOPERSTATE        33
#define COLUMN_SAAMFCOMPPRESENCESTATE        34
#define COLUMN_SAAMFCOMPREADINESSSTATE        35
#define COLUMN_SAAMFCOMPCURRPROXYNAME        36
#define COLUMN_SAAMFCOMPPROXYCSI        37
#define COLUMN_SAAMFCOMPRESTARTSTATE        38
#define COLUMN_SAAMFCOMPEAMTRIGGER        39
#define COLUMN_SAAMFCOMPROWSTATUS        40

/* column number definitions for table saAmfCompCSTypeSupportedTable */
#define COLUMN_SAAMFCOMPCSTYPESUPPORTEDCOMPNAMEID        1
#define COLUMN_SAAMFCOMPCSTYPESUPPORTEDCSTYPENAMEID        2
#define COLUMN_SAAMFCOMPCSTYPESUPPORTEDCOMPNAME        3
#define COLUMN_SAAMFCOMPCSTYPESUPPORTEDCSINAME        4
#define COLUMN_SAAMFCOMPCSTYPESUPPORTEDROWSTATUS        5

/* column number definitions for table saAmfCSITable */
#define COLUMN_SAAMFCSINAMEID        1
#define COLUMN_SAAMFCSINAME        2
#define COLUMN_SAAMFCSTYPE        3
#define COLUMN_SAAMFCSIROWSTATUS        5

/* column number definitions for table saAmfCSICSIDepTable */
#define COLUMN_SAAMFCSICSIDEPCSINAMEID        1
#define COLUMN_SAAMFCSICSIDEPDEPNDCSINAMEID        2
#define COLUMN_SAAMFCSICSIDEPCSINAME        3
#define COLUMN_SAAMFCSICSIDEPDEPNDCSINAME        4
#define COLUMN_SAAMFCSICSIDEPROWSTATUS        5

/* column number definitions for table saAmfCSINameValueTable */
#define COLUMN_SAAMFCSINAMEVALUECSINAMEID        1
#define COLUMN_SAAMFCSINAMEVALUEATTRNAMEID        2
#define COLUMN_SAAMFCSINAMEVALUECSINAME        3
#define COLUMN_SAAMFCSINAMEVALUEATTRNAME        4
#define COLUMN_SAAMFCSINAMEVALUEATTRVALUE        5
#define COLUMN_SAAMFCSINAMEVALUEROWSTATUS        6

/* column number definitions for table saAmfCSTypeAttrNameTable */
#define COLUMN_SAAMFCSTYPENAMEID        1
#define COLUMN_SAAMFCSTYPEATTRNAMEID        2
#define COLUMN_SAAMFCSTYPENAME        3
#define COLUMN_SAAMFCSTYPEATTRNAME        4
#define COLUMN_SAAMFCSTYPEATTRROWSTATUS        5

/* column number definitions for table saAmfSUSITable */
#define COLUMN_SAAMFSUSISUNAMEID        1
#define COLUMN_SAAMFSUSISINAMEID        2
#define COLUMN_SAAMFSUSISUNAME        3
#define COLUMN_SAAMFSUSISINAME        4
#define COLUMN_SAAMFSUSIHASTATE        5

/* column number definitions for table saAmfHealthCheckTable */
#define COLUMN_SAAMFHEALTHCOMPNAMEID        1
#define COLUMN_SAAMFHEALTHCHECKKEY        2
#define COLUMN_SAAMFHEALTHCOMPNAME        3
#define COLUMN_SAAMFHEALTHCHECKPERIOD        4
#define COLUMN_SAAMFHEALTHCHECKMAXDURATION        5
#define COLUMN_SAAMFHEALTHCHECKROWSTATUS        6

/* column number definitions for table saAmfSCompCsiTable */
#define COLUMN_SAAMFSCOMPCSICOMPNAMEID        1
#define COLUMN_SAAMFSCOMPCSICSINAMEID        2
#define COLUMN_SAAMFSCOMPCSICOMPNAME        3
#define COLUMN_SAAMFSCOMPCSICSINAME        4
#define COLUMN_SAAMFSCOMPCSIHASTATE        5

/* column number definitions for table saAmfProxyProxiedTable */
#define COLUMN_SAAMFPROXYPROXIEDPROXYNAMEID        1
#define COLUMN_SAAMFPROXYPROXIEDPROXIEDNAMEID        2
#define COLUMN_SAAMFPROXYPROXIEDPROXYNAME        3
#define COLUMN_SAAMFPROXYPROXIEDPROXIEDNAME        4

#ifdef __cplusplus
}
#endif

#endif /* _CL_SNMP_SAFAMF_COLUMNS_H */
