<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompileConfigs"
    nsURI="Comps.ecore" nsPrefix="CompileConfigs">
  <eClassifiers xsi:type="ecore:EClass" name="COR">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Clovis Object Repository"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="savetype" eType="#//SaveTypeEnum"
        defaultValueLiteral="CL_COR_DELTA_SAVE" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Save type"/>
        <details key="UItype" value="UISaveType"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SaveTypeEnum">
    <eLiterals name="CL_COR_DELTA_SAVE"/>
    <eLiterals name="CL_COR_NO_SAVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FM">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Fault Manager"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localProbationPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Local probation period(secs)"/>
        <details key="tooltip" value="Time period for which fault which is under local FM is stored in the system"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localSeqTableEntry" upperBound="-1"
        eType="#//SeqTableEntryType" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Local sequence table"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeqTableEntryType">
    <eAnnotations source="CWAnnotation">
      <details key="validationfeatures" value="Function"/>
      <details key="NameField" value="Function"/>
      <details key="label" value="Sequence Table"/>
      <details key="Help" value="com.clovis.cw.help.build_fm_seqtable"/>
      <details key="validator" value="com.clovis.cw.editor.ca:com.clovis.cw.editor.ca.validator.SequenceTableValidator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Category" eType="#//CategoryEnum"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Category"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Severity" eType="#//SeverityEnum"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Severity"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EscalationLevel" eType="#//EscalationLevelEnum"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Escalation Level"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Function Name"/>
        <details key="pattern" value="^[a-zA-Z][a-zA-Z0-9_]*$"/>
        <details key="message" value="Invalid Function Name"/>
        <details key="tooltip" value="Function to be executed upon fault occurance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsExtern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="extern?"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NS">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Name Service"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxentries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Maximum entries"/>
        <details key="tooltip" value="Maximum entries in the Name Service Table"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxglobalcontexts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Maximum global contexts"/>
        <details key="tooltip" value="Maximum no of global contexts(By Default 1 Global Context is provided)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxlocalcontexts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Maximum local contexts"/>
        <details key="tooltip" value="Maximum no of local contexts(By Default 1 Local Context is provided)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMD">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Remote Method Definition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxretries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Maximum retries"/>
        <details key="pattern" value="^([4-9]|[0-3][0-9])[0-9]*$"/>
        <details key="message" value="Maximim retries can not be less than 4"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentsInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="COR" eType="#//COR" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FM" eType="#//FM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NS" eType="#//NS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RMD" eType="#//RMD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PM" eType="#//PM" unsettable="true"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CategoryEnum">
    <eLiterals name="com"/>
    <eLiterals name="qos" value="1"/>
    <eLiterals name="proc" value="2"/>
    <eLiterals name="equip" value="3"/>
    <eLiterals name="env" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SeverityEnum">
    <eLiterals name="MN"/>
    <eLiterals name="WR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EscalationLevelEnum">
    <eLiterals name="Level1" value="1"/>
    <eLiterals name="Level2" value="2"/>
    <eLiterals name="Level3" value="3"/>
    <eLiterals name="Level4" value="4"/>
    <eLiterals name="Level5" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UISaveType" instanceClassName="">
    <eLiterals name="Delta save"/>
    <eLiterals name="No save" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PM">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="Performance Monitoring"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appConfigInterval" upperBound="-1"
        eType="#//AppConfigIntervalType" unsettable="true" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="PM Config Interval For Component Types"/>
        <details key="editor" value="com.clovis.cw.workspace:com.clovis.cw.workspace.dialog.PMConfigPushButtonCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compConfigInterval" upperBound="-1"
        eType="#//CompConfigIntervalType" unsettable="true" containment="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="PM Config Interval For Component Instances"/>
        <details key="editor" value="com.clovis.cw.workspace:com.clovis.cw.workspace.dialog.PMConfigPushButtonCellEditor"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppConfigIntervalType">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="PM Config Interval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Application Name"/>
        <details key="canModify" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3000" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Value (milliseconds)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompConfigIntervalType">
    <eAnnotations source="CWAnnotation">
      <details key="label" value="PM Config Interval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Component Name"/>
        <details key="canModify" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Component Type"/>
        <details key="isHidden" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true">
      <eAnnotations source="CWAnnotation">
        <details key="label" value="Value (milliseconds)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
