################################################################################
#
#   Copyright (C) 2002-2009 by OpenClovis Inc. All Rights  Reserved.
# 
#   The source code for this program is not published or otherwise divested
#   of its trade secrets, irrespective of what has been deposited with  the
#   U.S. Copyright office.
# 
#   No part of the source code  for this  program may  be use,  reproduced,
#   modified, transmitted, transcribed, stored  in a retrieval  system,  or
#   translated, in any form or by  any  means,  without  the prior  written
#   permission of OpenClovis Inc
################################################################################
#
# Build: 4.2.0
#
LIB_NAMES	= libev
SRC_FILES	= ev.c

include $(CLOVIS_ROOT)/ASP/mk/make-client.mk


	
