#!/bin/bash
export LD_LIBRARY_PATH=`pwd`/lib:`pwd`/plugin:$LD_LIBRARY_PATH
export PYTHONPATH=`pwd`/lib:`pwd`/bin:`pwd`/test:$PYTHONPATH

sysctl -w net.core.wmem_max=10485760
sysctl -w net.core.rmem_max=10485760
sysctl -w net.core.rmem_default=10485760
sysctl -w net.core.wmem_default=10485760

# To use UDP broadcasts on the loopback interface I need to enable a broadcast address
ifconfig lo broadcast 127.255.255.255

# excessive logging can cause expect's input buffer to fill up, hanging the app on stdout
export CL_LOG_SEVERITY=ERROR
export CL_LOG_CODE_LOCATION_ENABLE=1
export SAFPLUS_BACKPLANE_INTERFACE=lo

pkill -9 safplus_amf
# The group tests rely on a clean start because they check the number of existing groups after creating/deleting
./bin/safplus_cleanup
# Normally safplus_amf is the group server but for the unit tests we use the standalone group server
`pwd`/bin/safplus_group > safplus_group_server.log &

echo "complete"
