REL=$(shell source ../tools/docconfig_clovis.sh; echo $$RELEASE)

DOCID=evalguide
DOCTITLE=Evaluation System User Guide
DOCURL=Doc:sdk_$(REL)\/evalguide
PARTNUMBER=000105
INPUT_WIKI_FORMAT=multipage
OUTPUT_HTML_FORMAT=multipage2

# Makefile for generating html and pdf doc for Evaluation System Guide

include ../tools/Makefile.in
